// packages/app/frameworks/react-native-ui/src/components/Badge.tsx
/**
 * Badge component for React Native.
 *
 * @module
 */

import React from 'react'
import { Text, View } from 'react-native'

import type { BadgeProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders a Badge component.
 * @param root0 - Component props.
 * @param root0.children - Badge content.
 * @param root0.color - Badge color.
 * @param root0.variant - Visual variant style.
 * @param root0.size - Badge size.
 * @param root0.rounded - Whether rounded.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Badge element.
 */
export const Badge: React.FC<BadgeProps> = ({
  children,
  color = 'primary',
  variant: _variant = 'solid',
  size = 'md',
  rounded = true,
  className,
  testId,
}) => {
  const cm = getClassMap()
  const classes = cm.cn(cm.badge({ variant: color, size }), !rounded && cm.badgeSquare, className)

  return (
    <View className={classes} testID={testId}>
      <Text>{children as React.ReactNode}</Text>
    </View>
  )
}

// packages/app/frameworks/angular-ui/src/components/badge.component.ts
/**
 * Angular Badge UI component with UIClassMap-driven styling.
 *
 * @module
 */

import { ChangeDetectionStrategy, Component, Input } from '@angular/core'

import type { ColorVariant, Size, UIClassMap } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Angular Badge UI component with UIClassMap-driven styling.
 */
@Component({
  selector: 'mol-badge',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span [class]="badgeClasses" [style]="style" [attr.data-testid]="testId">
      <ng-content></ng-content>
    </span>
  `,
})
/**
 * Molecule Badge class.
 */
export class MoleculeBadge {
  @Input() color: ColorVariant = 'primary'
  @Input() variant: 'solid' | 'outline' | 'subtle' = 'solid'
  @Input() size?: Size
  @Input() rounded = true
  @Input() className?: string
  @Input() style?: Record<string, string>
  @Input() testId?: string

  /**
   * Retrieves the current UI class map.
   * @returns The UIClassMap instance for styling.
   */
  private get cm(): UIClassMap {
    return getClassMap()
  }

  /**
   * Computes the combined CSS classes for the badge element.
   * @returns The badge class name string.
   */
  get badgeClasses(): string {
    return this.cm.cn(
      this.cm.badge({ variant: this.color, size: this.size }),
      !this.rounded && this.cm.badgeSquare,
      this.className,
    )
  }
}
