// packages/app/frameworks/solid-ui/src/components/Button.tsx
/**
 * Button component.
 *
 * @module
 */

import { type Component, type JSX, Show, splitProps } from 'solid-js'

import type { ButtonProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { Spinner } from './Spinner.js'

/**
 * Renders the Button component.
 * @param props - The component props.
 * @returns The rendered button JSX.
 */
export const Button: Component<ButtonProps> = (props) => {
  const [local, rest] = splitProps(props, [
    'children',
    'variant',
    'color',
    'size',
    'loading',
    'loadingText',
    'fullWidth',
    'leftIcon',
    'rightIcon',
    'className',
    'style',
    'testId',
    'disabled',
    'type',
    'onClick',
  ])

  const cm = getClassMap()

  const classes = (): string =>
    cm.cn(
      cm.button({
        variant: local.variant,
        color: local.color,
        size: local.size,
        fullWidth: local.fullWidth,
      }),
      local.className,
    )

  return (
    <button
      type={local.type || 'button'}
      class={classes()}
      style={local.style}
      data-testid={local.testId}
      disabled={local.disabled || local.loading}
      onClick={local.onClick as JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent>}
      aria-busy={local.loading}
      {...(rest as JSX.ButtonHTMLAttributes<HTMLButtonElement>)}
    >
      <Show when={local.loading}>
        <Spinner size="sm" className={cm.buttonSpinner} />
      </Show>
      <Show when={!local.loading && !!local.leftIcon}>
        <span class={cm.buttonIconLeft}>{local.leftIcon as JSX.Element}</span>
      </Show>
      {local.loading && local.loadingText
        ? local.loadingText
        : (local.children as JSX.Element)}
      <Show when={!local.loading && !!local.rightIcon}>
        <span class={cm.buttonIconRight}>{local.rightIcon as JSX.Element}</span>
      </Show>
    </button>
  )
}

// packages/app/frameworks/angular-ui/src/components/button.component.ts
/**
 * Angular Button UI component with UIClassMap-driven styling.
 *
 * @module
 */

import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core'

import type { ButtonVariant, ColorVariant, Size, UIClassMap } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Angular Button UI component with UIClassMap-driven styling.
 */
@Component({
  selector: 'mol-button',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      [type]="type"
      [class]="classes"
      [style]="style"
      [attr.data-testid]="testId"
      [disabled]="disabled || loading"
      [attr.aria-busy]="loading"
      (click)="handleClick.emit($event)"
    >
      @if (loading) {
        <span [class]="cm.buttonSpinner"></span>
      }
      @if (loading && loadingText) {
        {{ loadingText }}
      } @else {
        <ng-content></ng-content>
      }
    </button>
  `,
})
/**
 * Molecule Button class.
 */
export class MoleculeButton {
  @Input() variant: ButtonVariant = 'solid'
  @Input() color: ColorVariant = 'primary'
  @Input() size: Size = 'md'
  @Input() loading = false
  @Input() loadingText?: string
  @Input() fullWidth = false
  @Input() className?: string
  @Input() style?: Record<string, string>
  @Input() testId?: string
  @Input() disabled = false
  @Input() type: 'button' | 'submit' | 'reset' = 'button'

  @Output() handleClick = new EventEmitter<MouseEvent>()

  /**
   * Retrieves the current UI class map.
   * @returns The UIClassMap instance for styling.
   */
  get cm(): UIClassMap {
    return getClassMap()
  }

  /**
   * Computes the combined CSS classes for the button element.
   * @returns The button class name string.
   */
  get classes(): string {
    return this.cm.cn(
      this.cm.button({
        variant: this.variant,
        color: this.color,
        size: this.size,
        fullWidth: this.fullWidth,
      }),
      this.className,
    )
  }
}
