// packages/app/frameworks/react-ui/src/components/Toast.tsx
/**
 * Toast component.
 *
 * @module
 */

import React, {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useState,
} from 'react'
import { createPortal } from 'react-dom'

import { t } from '@molecule/app-i18n'
import type { IconName } from '@molecule/app-icons'
import type { ColorVariant, ToastProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.js'

/**
 * Map status to toast variant.
 */
const statusVariantMap: Record<ColorVariant, 'default' | 'success' | 'warning' | 'error' | 'info'> =
  {
    primary: 'default',
    secondary: 'default',
    success: 'success',
    warning: 'warning',
    error: 'error',
    info: 'info',
  }

/**
 * Map toast status to icon name.
 */
const statusIconMap: Record<string, IconName> = {
  info: 'info-circle',
  success: 'check-circle',
  warning: 'exclamation-triangle',
  error: 'x-circle',
}

/**
 * Single Toast component.
 */
export const Toast = forwardRef<HTMLDivElement, ToastProps>(
  (
    {
      children,
      title,
      description,
      status = 'info',
      duration = 5000,
      dismissible = true,
      onDismiss,
      position: _position = 'bottom-right',
      closeLabel,
      className,
      style,
      testId,
    },
    ref,
  ) => {
    const [isVisible, setIsVisible] = useState(true)
    const cm = getClassMap()
    const variant = statusVariantMap[status] || 'default'
    const iconName = statusIconMap[variant]
    const statusIcon = iconName ? renderIcon(iconName, cm.iconMd) : null

    useEffect(() => {
      if (duration > 0) {
        const timer = setTimeout(() => {
          setIsVisible(false)
          onDismiss?.()
        }, duration)
        return () => clearTimeout(timer)
      }
    }, [duration, onDismiss])

    const handleDismiss = useCallback(() => {
      setIsVisible(false)
      onDismiss?.()
    }, [onDismiss])

    if (!isVisible) return null

    return (
      <div
        ref={ref}
        role="alert"
        data-state="open"
        className={cm.cn(cm.toast({ variant }), className)}
        style={style}
        data-testid={testId}
      >
        {statusIcon && <span className={cm.toastIconWrapper}>{statusIcon}</span>}
        <div className={cm.toastContentWrapper}>
          {title && <div className={cm.toastTitle}>{title}</div>}
          {!!(description || children) && (
            <div className={cm.toastDescription}>
              {(description as React.ReactNode) || (children as React.ReactNode)}
            </div>
          )}
        </div>
        {dismissible && (
          <button
            type="button"
            onClick={handleDismiss}
            className={cm.toastClose}
            aria-label={closeLabel ?? t('ui.toast.close', undefined, { defaultValue: 'Close' })}
          >
            {renderIcon('x-mark', cm.iconSm)}
          </button>
        )}
      </div>
    )
  },
)

Toast.displayName = 'Toast'

/**
 * Toast container for positioning toasts.
 */
interface ToastContainerProps {
  children?: React.ReactNode
  position?: ToastProps['position']
  className?: string
}

// positionClasses removed — use cm.toastContainer({ position }) instead

/**
 * Container that positions toasts on screen via a portal.
 * @returns The rendered toast container element.
 */
export const ToastContainer = forwardRef<HTMLDivElement, ToastContainerProps>(
  ({ children, position = 'bottom-right', className }, ref) => {
    const cm = getClassMap()

    const container = (
      <div ref={ref} className={cm.cn(cm.toastContainer({ position }), className)}>
        {children}
      </div>
    )

    if (typeof document === 'undefined') return null
    return createPortal(container, document.body)
  },
)

ToastContainer.displayName = 'ToastContainer'

/**
 * Toast context for managing toasts globally.
 */
interface ToastContextValue {
  toasts: (ToastProps & { id: string })[]
  addToast: (toast: Omit<ToastProps, 'onDismiss'>) => string
  removeToast: (id: string) => void
}

const ToastContext = createContext<ToastContextValue | null>(null)

/**
 * Hook to access the toast context for adding and removing toasts.
 * @returns The toast context value with toast management methods.
 */
export const useToast = (): ToastContextValue => {
  const context = useContext(ToastContext)
  if (!context) {
    throw new Error(
      t('react.error.useToastOutsideProvider', undefined, {
        defaultValue: 'useToast must be used within a ToastProvider',
      }),
    )
  }
  return context
}

interface ToastProviderProps {
  children: React.ReactNode
  position?: ToastProps['position']
}

let toastCounter = 0

/**
 * Provider component that manages global toast state.
 * @param root0 - The component props.
 * @param root0.children - The child elements to render within the provider.
 * @param root0.position - The default position for toasts.
 * @returns The rendered provider with toast container.
 */
export const ToastProvider: React.FC<ToastProviderProps> = ({
  children,
  position = 'bottom-right',
}) => {
  const [toasts, setToasts] = useState<(ToastProps & { id: string })[]>([])

  const addToast = useCallback((toast: Omit<ToastProps, 'onDismiss'>) => {
    const id = `toast-${++toastCounter}`
    setToasts((prev) => [...prev, { ...toast, id }])
    return id
  }, [])

  const removeToast = useCallback((id: string) => {
    setToasts((prev) => prev.filter((t) => t.id !== id))
  }, [])

  return (
    <ToastContext.Provider value={{ toasts, addToast, removeToast }}>
      {children}
      <ToastContainer position={position}>
        {toasts.map((toast) => (
          <Toast key={toast.id} {...toast} onDismiss={() => removeToast(toast.id)} />
        ))}
      </ToastContainer>
    </ToastContext.Provider>
  )
}

// packages/app/frameworks/angular-ui/src/components/toast.component.ts
/**
 * Angular Toast UI component with UIClassMap-driven styling.
 *
 * @module
 */

import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  type OnDestroy,
  type OnInit,
  Output,
} from '@angular/core'

import { t } from '@molecule/app-i18n'
import type { ColorVariant, UIClassMap } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import type { IconName } from '@molecule/app-icons'
import { getIconSvg } from '../utilities/render-icon.js'

const statusVariantMap: Record<ColorVariant, 'default' | 'success' | 'warning' | 'error' | 'info'> =
  {
    primary: 'default',
    secondary: 'default',
    success: 'success',
    warning: 'warning',
    error: 'error',
    info: 'info',
  }

/**
 * Angular Toast UI component with UIClassMap-driven styling.
 */
@Component({
  selector: 'mol-toast',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (isVisible) {
      <div
        role="alert"
        data-state="open"
        [class]="toastClasses"
        [style]="style"
        [attr.data-testid]="testId"
      >
        @if (showIcon) {
          <span [class]="cm.toastIconWrapper">
            <span [innerHTML]="statusIconSvg"></span>
          </span>
        }
        <div [class]="cm.toastContentWrapper">
          @if (title) {
            <div [class]="titleClass">{{ title }}</div>
          }
          @if (description) {
            <div [class]="descriptionClass">{{ description }}</div>
          } @else {
            <div [class]="descriptionClass">
              <ng-content></ng-content>
            </div>
          }
        </div>
        @if (dismissible) {
          <button
            type="button"
            (click)="onDismiss()"
            [class]="closeButtonClass"
            [attr.aria-label]="closeAriaLabel"
          >
            <span [innerHTML]="dismissIconSvg"></span>
          </button>
        }
      </div>
    }
  `,
})
/**
 * Molecule Toast class.
 */
export class MoleculeToast implements OnInit, OnDestroy {
  @Input() title?: string
  @Input() description?: string
  @Input() status: ColorVariant = 'info'
  @Input() duration = 5000
  @Input() dismissible = true
  @Input() closeLabel?: string
  @Input() position: 'top' | 'top-right' | 'top-left' | 'bottom' | 'bottom-right' | 'bottom-left' =
    'bottom-right'
  @Input() className?: string
  @Input() style?: Record<string, string>
  @Input() testId?: string

  @Output() dismiss = new EventEmitter<void>()

  isVisible = true
  private timer?: ReturnType<typeof setTimeout>

  /**
   * Retrieves the current UI class map.
   * @returns The UIClassMap instance for styling.
   */
  get cm(): UIClassMap {
    return getClassMap()
  }

  /**
   * Computes the accessible close button label.
   * @returns The localized aria-label for the close button.
   */
  get closeAriaLabel(): string {
    return this.closeLabel || t('ui.toast.close', undefined, { defaultValue: 'Close' })
  }

  /**
   * Retrieves the CSS class for the toast title.
   * @returns The title class name string.
   */
  get titleClass(): string {
    return this.cm.toastTitle
  }

  /**
   * Retrieves the CSS class for the toast description.
   * @returns The description class name string.
   */
  get descriptionClass(): string {
    return this.cm.toastDescription
  }

  /**
   * Retrieves the CSS class for the close button.
   * @returns The close button class name string.
   */
  get closeButtonClass(): string {
    return this.cm.toastClose
  }

  /**
   * Determines the icon type based on the toast status.
   * @returns The mapped icon type string.
   */
  get iconType(): string {
    return statusVariantMap[this.status] || 'default'
  }

  /**
   * Determines whether the status icon should be shown.
   * @returns True if the icon type is not default.
   */
  get showIcon(): boolean {
    return this.iconType !== 'default'
  }

  private statusIconMap: Record<string, IconName> = {
    info: 'info-circle',
    success: 'check-circle',
    warning: 'exclamation-triangle',
    error: 'x-circle',
  }

  /**
   * Generates the SVG markup for the status icon.
   * @returns The SVG string for the current status icon.
   */
  get statusIconSvg(): string {
    const name = this.statusIconMap[this.iconType]
    return name ? getIconSvg(name, this.cm.iconMd) : ''
  }

  /**
   * Generates the SVG markup for the dismiss icon.
   * @returns The SVG string for the dismiss button icon.
   */
  get dismissIconSvg(): string {
    return getIconSvg('x-mark', this.cm.iconSm)
  }

  /**
   * Computes the combined CSS classes for the toast container.
   * @returns The toast class name string.
   */
  get toastClasses(): string {
    const variant = statusVariantMap[this.status] || 'default'
    return this.cm.cn(this.cm.toast({ variant }), this.className)
  }

  /**
   * Starts the auto-dismiss timer on component creation.
   */
  ngOnInit(): void {
    if (this.duration > 0) {
      this.timer = setTimeout(() => {
        this.isVisible = false
        this.dismiss.emit()
      }, this.duration)
    }
  }

  /**
   * Clears the auto-dismiss timer on component destruction.
   */
  ngOnDestroy(): void {
    if (this.timer) {
      clearTimeout(this.timer)
    }
  }

  /**
   * Handles the dismiss action by hiding the toast.
   */
  onDismiss(): void {
    this.isVisible = false
    this.dismiss.emit()
  }
}
