// packages/app/frameworks/solid-ui/src/components/Badge.tsx
/**
 * Badge component.
 *
 * @module
 */

import { type Component, type JSX, splitProps } from 'solid-js'

import type { BadgeProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the Badge component.
 * @param props - The component props.
 * @returns The rendered badge JSX.
 */
export const Badge: Component<BadgeProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'color',
    'variant',
    'size',
    'rounded',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()

  const badgeClasses = (): string =>
    cm.cn(
      cm.badge({ variant: local.color, size: local.size }),
      !(local.rounded ?? true) && cm.badgeSquare,
      local.className,
    )

  return (
    <span class={badgeClasses()} style={local.style} data-testid={local.testId}>
      {local.children as JSX.Element}
    </span>
  )
}

// packages/app/frameworks/react-ui/src/components/Badge.tsx
/**
 * Badge component.
 *
 * @module
 */

import React, { forwardRef } from 'react'

import type { BadgeProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Badge component.
 */
export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
  (
    {
      children,
      color = 'primary',
      variant: _variant = 'solid',
      size,
      rounded = true,
      className,
      style,
      testId,
    },
    ref,
  ) => {
    const cm = getClassMap()

    const badgeClasses = cm.cn(
      cm.badge({ variant: color, size }),
      !rounded && cm.badgeSquare,
      className,
    )

    return (
      <span ref={ref} className={badgeClasses} style={style} data-testid={testId}>
        {children as React.ReactNode}
      </span>
    )
  },
)

Badge.displayName = 'Badge'
