// packages/app/frameworks/solid-ui/src/components/Checkbox.tsx
/**
 * Checkbox component.
 *
 * @module
 */

import { type Component, createEffect, type JSX, Show, splitProps } from 'solid-js'

import type { CheckboxProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the Checkbox component.
 * @param props - The component props.
 * @returns The rendered checkbox JSX.
 */
export const Checkbox: Component<CheckboxProps> = (props) => {
  const [local, rest] = splitProps(props, [
    'label',
    'checked',
    'indeterminate',
    'size',
    'error',
    'className',
    'style',
    'testId',
    'disabled',
    'name',
    'id',
    'onChange',
  ])

  const cm = getClassMap()
  // eslint-disable-next-line no-unassigned-vars -- assigned via SolidJS ref binding
  let checkboxRef: HTMLInputElement | undefined

  const checkboxId = (): string | undefined => local.id || local.name

  createEffect(() => {
    if (checkboxRef) {
      checkboxRef.indeterminate = !!local.indeterminate
    }
  })

  const checkboxClasses = (): string =>
    cm.cn(cm.checkbox({ error: !!local.error }), local.className)

  return (
    <div class={cm.formFieldWrapper}>
      <label class={cm.controlLabel}>
        <input
          ref={checkboxRef}
          type="checkbox"
          id={checkboxId()}
          name={local.name}
          checked={local.checked}
          disabled={local.disabled}
          data-state={local.checked ? 'checked' : 'unchecked'}
          aria-invalid={!!local.error}
          class={checkboxClasses()}
          style={local.style}
          data-testid={local.testId}
          onChange={local.onChange as JSX.EventHandlerUnion<HTMLInputElement, Event>}
          {...(rest as JSX.InputHTMLAttributes<HTMLInputElement>)}
        />
        <Show when={!!local.label}>
          <span class={cm.cn(cm.controlText, local.disabled && cm.controlDisabled)}>
            {local.label as JSX.Element}
          </span>
        </Show>
      </label>
      <Show when={local.error}>
        <p class={cm.cn(cm.formError, cm.sp('mt', 1))}>{local.error}</p>
      </Show>
    </div>
  )
}

// packages/app/frameworks/react-ui/src/components/Checkbox.tsx
/**
 * Checkbox component.
 *
 * @module
 */

import React, { forwardRef, useEffect, useRef } from 'react'

import type { CheckboxProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Checkbox component.
 */
export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(
  (
    {
      label,
      checked,
      indeterminate,
      size: _size,
      error,
      className,
      style,
      testId,
      disabled,
      name,
      id,
      onChange,
      ...rest
    },
    ref,
  ) => {
    const internalRef = useRef<HTMLInputElement>(null)
    const checkboxRef = (ref || internalRef) as React.RefObject<HTMLInputElement>

    const cm = getClassMap()
    const checkboxId = id || name

    useEffect(() => {
      if (checkboxRef.current) {
        checkboxRef.current.indeterminate = !!indeterminate
      }
    }, [indeterminate])

    const checkboxClasses = cm.cn(cm.checkbox({ error: !!error }), className)

    return (
      <div className={cm.formFieldWrapper}>
        <label className={cm.controlLabel}>
          <input
            ref={checkboxRef}
            type="checkbox"
            id={checkboxId}
            name={name}
            checked={checked}
            disabled={disabled}
            data-state={checked ? 'checked' : 'unchecked'}
            aria-invalid={!!error}
            className={checkboxClasses}
            style={style}
            data-testid={testId}
            onChange={onChange as unknown as React.ChangeEventHandler<HTMLInputElement>}
            {...(rest as React.InputHTMLAttributes<HTMLInputElement>)}
          />
          {!!label && (
            <span className={cm.cn(cm.controlText, disabled && cm.controlDisabled)}>
              {label as React.ReactNode}
            </span>
          )}
        </label>
        {error && <p className={cm.cn(cm.formError, cm.sp('mt', 1))}>{error}</p>}
      </div>
    )
  },
)

Checkbox.displayName = 'Checkbox'
