// packages/app/frameworks/solid-ui/src/components/Form.tsx
/**
 * Form components.
 *
 * @module
 */

import { type Component, type JSX, Show, splitProps } from 'solid-js'

import type { FormFieldProps, FormProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Form component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Form: Component<FormProps> = (props) => {
  const [local, rest] = splitProps(props, [
    'children',
    'onFormSubmit',
    'submitting',
    'className',
    'style',
    'testId',
    'onSubmit',
    'action',
    'method',
    'noValidate',
  ])

  const cm = getClassMap()

  const handleSubmit: JSX.EventHandlerUnion<HTMLFormElement, Event> = (e) => {
    if (local.onFormSubmit) {
      e.preventDefault()
      const formData = new FormData(e.currentTarget)
      const data: Record<string, unknown> = {}
      formData.forEach((value, key) => {
        data[key] = value
      })
      local.onFormSubmit(data)
    }
    local.onSubmit?.(e as unknown as Event)
  }

  return (
    <form
      class={local.className}
      style={local.style}
      data-testid={local.testId}
      action={local.action}
      method={local.method}
      noValidate={local.noValidate}
      onSubmit={handleSubmit}
      {...(rest as JSX.FormHTMLAttributes<HTMLFormElement>)}
    >
      <fieldset disabled={local.submitting} class={cm.formFieldsetContents}>
        {local.children as JSX.Element}
      </fieldset>
    </form>
  )
}

/**
 * Form field wrapper component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const FormField: Component<FormFieldProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'label',
    'name',
    'error',
    'hint',
    'required',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()

  return (
    <div
      class={cm.cn(cm.formField, local.className)}
      style={local.style}
      data-testid={local.testId}
    >
      <Show when={local.label}>
        <label
          for={local.name}
          class={cm.cn(cm.label({ required: local.required }), cm.labelBlock)}
        >
          {local.label}
        </label>
      </Show>
      {local.children as JSX.Element}
      <Show when={local.error}>
        <p id={`${local.name}-error`} class={cm.formError}>
          {local.error}
        </p>
      </Show>
      <Show when={local.hint && !local.error}>
        <p id={`${local.name}-hint`} class={cm.formHint}>
          {local.hint}
        </p>
      </Show>
    </div>
  )
}

/**
 * Label component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Label: Component<{
  children?: JSX.Element
  required?: boolean
  class?: string
  for?: string
}> = (props) => {
  const cm = getClassMap()
  return (
    <label for={props.for} class={cm.cn(cm.label({ required: props.required }), props.class)}>
      {props.children}
    </label>
  )
}

// packages/app/frameworks/react-ui/src/components/Form.tsx
/**
 * Form components.
 *
 * @module
 */

import React, { forwardRef } from 'react'

import type { FormFieldProps,FormProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Form component.
 */
export const Form = forwardRef<HTMLFormElement, FormProps>(
  (
    {
      children,
      onFormSubmit,
      submitting,
      className,
      style,
      testId,
      onSubmit,
      action,
      method,
      noValidate,
      ...rest
    },
    ref,
  ) => {
    const cm = getClassMap()
    const handleSubmit = (e: React.FormEvent<HTMLFormElement>): void => {
      if (onFormSubmit) {
        e.preventDefault()
        const formData = new FormData(e.currentTarget)
        const data: Record<string, unknown> = {}
        formData.forEach((value, key) => {
          data[key] = value
        })
        onFormSubmit(data)
      }
      onSubmit?.(e as unknown as Event)
    }

    return (
      <form
        ref={ref}
        className={className}
        style={style}
        data-testid={testId}
        action={action}
        method={method}
        noValidate={noValidate}
        onSubmit={handleSubmit}
        {...(rest as React.FormHTMLAttributes<HTMLFormElement>)}
      >
        <fieldset disabled={submitting} className={cm.formFieldsetContents}>
          {children as React.ReactNode}
        </fieldset>
      </form>
    )
  },
)

Form.displayName = 'Form'

/**
 * Form field wrapper component.
 */
export const FormField = forwardRef<HTMLDivElement, FormFieldProps>(
  ({ children, label, name, error, hint, required, className, style, testId }, ref) => {
    const cm = getClassMap()

    return (
      <div ref={ref} className={cm.cn(cm.inputWrapper, cm.sp('mb', 4), className)} style={style} data-testid={testId}>
        {label && (
          <label
            htmlFor={name}
            className={cm.cn(cm.label({ required: !!required }), cm.labelBlock)}
          >
            {label}
          </label>
        )}
        {children as React.ReactNode}
        {error && (
          <p id={`${name}-error`} className={cm.formError}>
            {error}
          </p>
        )}
        {hint && !error && (
          <p id={`${name}-hint`} className={cm.formHint}>
            {hint}
          </p>
        )}
      </div>
    )
  },
)

FormField.displayName = 'FormField'

/**
 * Label component.
 */
export const Label = forwardRef<
  HTMLLabelElement,
  React.LabelHTMLAttributes<HTMLLabelElement> & { required?: boolean }
>(({ children, required, className, ...props }, ref) => {
  const cm = getClassMap()

  return (
    <label ref={ref} className={cm.cn(cm.label({ required: !!required }), className)} {...props}>
      {children}
    </label>
  )
})

Label.displayName = 'Label'
