// packages/app/frameworks/angular-ui/src/components/select.component.ts
/**
 * Angular Select UI component with UIClassMap-driven styling.
 *
 * @module
 */

import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core'

import type { SelectOption, Size, UIClassMap } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Angular Select UI component with UIClassMap-driven styling.
 */
@Component({
  selector: 'mol-select',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="cm.inputWrapper">
      @if (label) {
        <label [attr.for]="selectId" [class]="labelClasses">
          {{ label }}
        </label>
      }
      <div [class]="cm.inputInner">
        <select
          [id]="selectId"
          [name]="name"
          [value]="value"
          [disabled]="disabled"
          [required]="required"
          [attr.aria-invalid]="!!error"
          [attr.aria-describedby]="ariaDescribedBy"
          [class]="selectClasses"
          [attr.data-testid]="testId"
          (change)="onSelectChange($event)"
        >
          @if (placeholder) {
            <option value="" disabled>{{ placeholder }}</option>
          }
          @if (clearable) {
            <option value="">--</option>
          }
          @for (option of options; track option.value) {
            <option [value]="option.value" [disabled]="option.disabled">
              {{ option.label }}
            </option>
          }
        </select>
      </div>
      @if (error) {
        <p [id]="selectId + '-error'" [class]="formErrorClass">
          {{ error }}
        </p>
      }
      @if (hint && !error) {
        <p [id]="selectId + '-hint'" [class]="formHintClass">
          {{ hint }}
        </p>
      }
    </div>
  `,
})
/**
 * Molecule Select class.
 */
export class MoleculeSelect {
  @Input() options: SelectOption<string>[] = []
  @Input() value?: string
  @Input() size: Size = 'md'
  @Input() label?: string
  @Input() placeholder?: string
  @Input() error?: string
  @Input() hint?: string
  @Input() clearable = false
  @Input() className?: string
  @Input() testId?: string
  @Input() disabled = false
  @Input() required = false
  @Input() name?: string
  @Input() id?: string

  @Output() valueChange = new EventEmitter<string>()
  @Output() handleChange = new EventEmitter<Event>()

  /**
   * Retrieves the current UI class map.
   * @returns The UIClassMap instance for styling.
   */
  get cm(): UIClassMap {
    return getClassMap()
  }

  /**
   * Retrieves the CSS class for form error messages.
   * @returns The form error class name string.
   */
  get formErrorClass(): string {
    return this.cm.formError
  }

  /**
   * Retrieves the CSS class for form hint messages.
   * @returns The form hint class name string.
   */
  get formHintClass(): string {
    return this.cm.formHint
  }

  /**
   * Resolves the select element ID.
   * @returns The resolved ID from the id or name input.
   */
  get selectId(): string {
    return this.id || this.name || ''
  }

  /**
   * Computes the aria-describedby attribute value.
   * @returns The ID of the describing element, or null if none.
   */
  get ariaDescribedBy(): string | null {
    if (this.error) return `${this.selectId}-error`
    if (this.hint) return `${this.selectId}-hint`
    return null
  }

  /**
   * Computes the CSS classes for the select label.
   * @returns The label class name string.
   */
  get labelClasses(): string {
    return this.cm.cn(this.cm.label({ required: this.required }), this.cm.labelBlock)
  }

  /**
   * Computes the combined CSS classes for the select element.
   * @returns The select class name string.
   */
  get selectClasses(): string {
    return this.cm.cn(
      this.cm.select({ error: !!this.error, size: this.size }),
      this.cm.selectNative,
      this.className,
    )
  }

  /**
   * Handles select value change events.
   * @param event - The change event from the select element.
   */
  onSelectChange(event: Event): void {
    const target = event.target as HTMLSelectElement
    this.handleChange.emit(event)
    this.valueChange.emit(target.value)
  }
}

// packages/app/frameworks/react-ui/src/components/Select.tsx
/**
 * Select component.
 *
 * @module
 */

import React, { forwardRef } from 'react'

import { getIconDataUrl } from '@molecule/app-icons'
import type { SelectProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Select component.
 */
export const Select = forwardRef<HTMLSelectElement, SelectProps<string>>(
  (
    {
      options,
      value,
      onValueChange,
      size = 'md',
      label,
      placeholder,
      error,
      hint,
      clearable,
      className,
      style,
      testId,
      disabled,
      required,
      name,
      id,
      onChange,
      ...rest
    },
    ref,
  ) => {
    const cm = getClassMap()
    const selectId = id || name

    const selectClasses = cm.cn(cm.select({ error: !!error, size }), cm.selectNative, className)

    // Group options by group property
    const groupedOptions = options.reduce<Record<string, typeof options>>((acc, option) => {
      const group = option.group || ''
      if (!acc[group]) {
        acc[group] = []
      }
      acc[group].push(option)
      return acc
    }, {})

    const handleChange = (e: React.ChangeEvent<HTMLSelectElement>): void => {
      onChange?.(e as unknown as Event)
      onValueChange?.(e.target.value)
    }

    const renderOptions = (): React.ReactNode => {
      const groups = Object.entries(groupedOptions)

      if (groups.length === 1 && groups[0][0] === '') {
        // No groups, render flat options
        return groups[0][1].map((option) => (
          <option key={option.value} value={option.value} disabled={option.disabled}>
            {option.label}
          </option>
        ))
      }

      // Render grouped options
      return groups.map(([group, groupOptions]) => {
        if (group === '') {
          return groupOptions.map((option) => (
            <option key={option.value} value={option.value} disabled={option.disabled}>
              {option.label}
            </option>
          ))
        }

        return (
          <optgroup key={group} label={group}>
            {groupOptions.map((option) => (
              <option key={option.value} value={option.value} disabled={option.disabled}>
                {option.label}
              </option>
            ))}
          </optgroup>
        )
      })
    }

    return (
      <div className={cm.inputWrapper}>
        {label && (
          <label
            htmlFor={selectId}
            className={cm.cn(cm.label({ required: !!required }), cm.labelBlock)}
          >
            {label}
          </label>
        )}
        <div className={cm.inputInner}>
          <select
            ref={ref}
            id={selectId}
            name={name}
            value={value}
            disabled={disabled}
            required={required}
            aria-invalid={!!error}
            aria-describedby={error ? `${selectId}-error` : hint ? `${selectId}-hint` : undefined}
            className={selectClasses}
            style={{
              ...style,
              backgroundImage: getIconDataUrl('chevron-down', '#6b7280'),
              backgroundPosition: 'right 0.5rem center',
              backgroundSize: '1.5em 1.5em',
            }}
            data-testid={testId}
            onChange={handleChange}
            {...(rest as React.SelectHTMLAttributes<HTMLSelectElement>)}
          >
            {placeholder && (
              <option value="" disabled>
                {placeholder}
              </option>
            )}
            {clearable && <option value="">--</option>}
            {renderOptions()}
          </select>
        </div>
        {error && (
          <p id={`${selectId}-error`} className={cm.formError}>
            {error}
          </p>
        )}
        {hint && !error && (
          <p id={`${selectId}-hint`} className={cm.formHint}>
            {hint}
          </p>
        )}
      </div>
    )
  },
)

Select.displayName = 'Select'
