// packages/app/frameworks/solid-ui/src/components/Skeleton.tsx
/**
 * Skeleton component.
 *
 * @module
 */

import { type Component, For, splitProps } from 'solid-js'

import type { SkeletonProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Skeleton component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Skeleton: Component<SkeletonProps> = (props) => {
  const [local] = splitProps(props, [
    'width',
    'height',
    'circle',
    'borderRadius',
    'animation',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const animation = (): string => local.animation ?? 'pulse'

  const skeletonClasses = (): string =>
    cm.cn(
      cm.skeleton(),
      local.circle && cm.skeletonCircle,
      animation() === 'none' && cm.skeletonNone,
      animation() === 'wave' && cm.skeletonWave,
      local.className,
    )

  const computedStyle = (): Record<string, string | undefined> => {
    const style: Record<string, string | undefined> = {
      ...local.style,
      width: typeof local.width === 'number' ? `${local.width}px` : local.width,
      height: typeof local.height === 'number' ? `${local.height}px` : local.height,
      'border-radius': local.circle
        ? '9999px'
        : typeof local.borderRadius === 'number'
          ? `${local.borderRadius}px`
          : local.borderRadius,
    }

    // If circle, make width and height equal
    if (local.circle && local.width && !local.height) {
      style.height = style.width
    }

    return style
  }

  return <div class={skeletonClasses()} style={computedStyle()} data-testid={local.testId} />
}

/**
 * Skeleton text line.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const SkeletonText: Component<{ lines?: number; class?: string }> = (props) => {
  const cm = getClassMap()
  const lines = (): number => props.lines ?? 3
  return (
    <div class={cm.cn(cm.skeletonTextContainer, props.class)}>
      <For each={Array.from({ length: lines() })}>
        {(_, i) => <Skeleton height={16} width={i() === lines() - 1 ? '60%' : '100%'} />}
      </For>
    </div>
  )
}

/**
 * Skeleton circle (avatar placeholder).
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const SkeletonCircle: Component<{ size?: number; class?: string }> = (props) => {
  const size = (): number => props.size ?? 40
  return <Skeleton circle width={size()} height={size()} className={props.class} />
}

// packages/app/frameworks/react-ui/src/components/Skeleton.tsx
/**
 * Skeleton component.
 *
 * @module
 */

import React, { forwardRef } from 'react'

import type { SkeletonProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Skeleton component.
 */
export const Skeleton = forwardRef<HTMLDivElement, SkeletonProps>(
  ({ width, height, circle, borderRadius, animation = 'pulse', className, style, testId }, ref) => {
    const cm = getClassMap()

    const skeletonClasses = cm.cn(
      cm.skeleton(),
      circle && cm.skeletonCircle,
      animation === 'none' && cm.skeletonNone,
      animation === 'wave' && cm.skeletonWave,
      className,
    )

    const computedStyle: React.CSSProperties = {
      ...style,
      width: typeof width === 'number' ? `${width}px` : width,
      height: typeof height === 'number' ? `${height}px` : height,
      borderRadius: circle
        ? '9999px'
        : typeof borderRadius === 'number'
          ? `${borderRadius}px`
          : borderRadius,
    }

    // If circle, make width and height equal
    if (circle && width && !height) {
      computedStyle.height = computedStyle.width
    }

    return <div ref={ref} className={skeletonClasses} style={computedStyle} data-testid={testId} />
  },
)

Skeleton.displayName = 'Skeleton'

/**
 * Skeleton text line.
 */
export const SkeletonText = forwardRef<HTMLDivElement, { lines?: number; className?: string }>(
  ({ lines = 3, className }, ref) => {
    const cm = getClassMap()

    return (
      <div ref={ref} className={cm.cn(cm.skeletonTextContainer, className)}>
        {Array.from({ length: lines }).map((_, i) => (
          <Skeleton key={i} height={16} width={i === lines - 1 ? '60%' : '100%'} />
        ))}
      </div>
    )
  },
)

SkeletonText.displayName = 'SkeletonText'

/**
 * Skeleton circle (avatar placeholder).
 */
export const SkeletonCircle = forwardRef<HTMLDivElement, { size?: number; className?: string }>(
  ({ size = 40, className }, ref) => (
    <Skeleton ref={ref} circle width={size} height={size} className={className} />
  ),
)

SkeletonCircle.displayName = 'SkeletonCircle'
