// packages/app/frameworks/solid-ui/src/components/Switch.tsx
/**
 * Switch component.
 *
 * @module
 */

import { type Component, type JSX, Show, splitProps } from 'solid-js'

import type { SwitchProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the Switch component.
 * @param props - The component props.
 * @returns The rendered switch JSX.
 */
export const Switch: Component<SwitchProps> = (props) => {
  const [local, rest] = splitProps(props, [
    'label',
    'checked',
    'size',
    'color',
    'className',
    'style',
    'testId',
    'disabled',
    'onChange',
  ])

  const cm = getClassMap()
  const state = (): 'checked' | 'unchecked' => (local.checked ? 'checked' : 'unchecked')

  const handleClick = (): void => {
    if (!local.disabled) {
      // Simulate a change event
      const event = { target: { checked: !local.checked } } as unknown as Event
      local.onChange?.(event)
    }
  }

  return (
    <label class={cm.cn(cm.controlLabel, local.disabled && cm.controlDisabled)}>
      <button
        type="button"
        role="switch"
        aria-checked={local.checked}
        disabled={local.disabled}
        data-state={state()}
        onClick={handleClick}
        class={cm.cn(cm.switchBase({ size: local.size }), local.className)}
        style={local.style}
        data-testid={local.testId}
        {...(rest as JSX.ButtonHTMLAttributes<HTMLButtonElement>)}
      >
        <span data-state={state()} class={cm.switchThumb({ size: local.size })} />
      </button>
      <Show when={!!local.label}>
        <span class={cm.controlText}>{local.label as JSX.Element}</span>
      </Show>
    </label>
  )
}

// packages/app/frameworks/react-ui/src/components/Switch.tsx
/**
 * Switch component.
 *
 * @module
 */

import React, { forwardRef } from 'react'

import type { SwitchProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Switch component.
 */
export const Switch = forwardRef<HTMLButtonElement, SwitchProps>(
  (
    { label, checked, size = 'md', color: _color, className, style, testId, disabled, onChange, ...rest },
    ref,
  ) => {
    const cm = getClassMap()
    const state = checked ? 'checked' : 'unchecked'

    const handleClick = (): void => {
      if (!disabled) {
        // Simulate a change event
        const event = { target: { checked: !checked } } as unknown as Event
        onChange?.(event)
      }
    }

    return (
      <label
        className={cm.cn(
          cm.controlLabel,
          disabled && cm.controlDisabled,
        )}
      >
        <button
          ref={ref}
          type="button"
          role="switch"
          aria-checked={checked}
          disabled={disabled}
          data-state={state}
          onClick={handleClick}
          className={cm.cn(cm.switchBase({ size }), className)}
          style={style}
          data-testid={testId}
          {...(rest as React.ButtonHTMLAttributes<HTMLButtonElement>)}
        >
          <span data-state={state} className={cm.switchThumb({ size })} />
        </button>
        {!!label && <span className={cm.controlText}>{label as React.ReactNode}</span>}
      </label>
    )
  },
)

Switch.displayName = 'Switch'
