// packages/app/frameworks/solid-ui/src/components/Tabs.tsx
/**
 * Tabs component.
 *
 * @module
 */

import { type Component, createSignal, For, type JSX, Show, splitProps } from 'solid-js'

import type { TabsProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Tabs component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Tabs: Component<TabsProps<string>> = (props) => {
  const [local] = splitProps(props, [
    'items',
    'value',
    'defaultValue',
    'onChange',
    'variant',
    'size',
    'fitted',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const [internalValue, setInternalValue] = createSignal(
    local.defaultValue || local.items[0]?.value,
  )
  const activeValue = (): string | undefined =>
    local.value !== undefined ? local.value : internalValue()

  const handleTabClick = (tabValue: string): void => {
    if (local.value === undefined) {
      setInternalValue(tabValue)
    }
    local.onChange?.(tabValue)
  }

  const activeItem = (): (typeof local.items)[number] | undefined =>
    local.items.find((item) => item.value === activeValue())

  return (
    <div class={local.className} style={local.style} data-testid={local.testId}>
      <div class={cm.cn(cm.tabsList, local.fitted && cm.tabsFitted)} role="tablist">
        <For each={local.items}>
          {(item) => {
            const isActive = (): boolean => item.value === activeValue()
            return (
              <button
                type="button"
                role="tab"
                aria-selected={isActive()}
                aria-controls={`tabpanel-${item.value}`}
                data-state={isActive() ? 'active' : 'inactive'}
                disabled={item.disabled}
                onClick={() => handleTabClick(item.value)}
                class={cm.cn(cm.tabsTrigger, local.fitted && cm.tabTriggerFitted)}
              >
                <Show when={!!item.icon}>
                  <span class={cm.tabTriggerIcon}>{item.icon as JSX.Element}</span>
                </Show>
                {item.label as JSX.Element}
              </button>
            )
          }}
        </For>
      </div>
      <Show when={!!activeItem()?.content}>
        <div
          role="tabpanel"
          id={`tabpanel-${activeValue()}`}
          aria-labelledby={activeValue()}
          class={cm.tabsContent}
        >
          {activeItem()!.content as JSX.Element}
        </div>
      </Show>
    </div>
  )
}

// packages/app/frameworks/react-ui/src/components/Tabs.tsx
/**
 * Tabs component.
 *
 * @module
 */

import React, { forwardRef, useState } from 'react'

import type { TabsProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Tabs component.
 */
export const Tabs = forwardRef<HTMLDivElement, TabsProps<string>>(
  (
    { items, value, defaultValue, onChange, variant: _variant, size: _size, fitted, className, style, testId },
    ref,
  ) => {
    const [internalValue, setInternalValue] = useState(defaultValue || items[0]?.value)
    const activeValue = value !== undefined ? value : internalValue

    const cm = getClassMap()

    const handleTabClick = (tabValue: string): void => {
      if (value === undefined) {
        setInternalValue(tabValue)
      }
      onChange?.(tabValue)
    }

    const activeItem = items.find((item) => item.value === activeValue)

    return (
      <div ref={ref} className={className} style={style} data-testid={testId}>
        <div className={cm.cn(cm.tabsList, fitted && cm.tabsFitted)} role="tablist">
          {items.map((item) => {
            const isActive = item.value === activeValue
            return (
              <button
                key={item.value}
                type="button"
                role="tab"
                aria-selected={isActive}
                aria-controls={`tabpanel-${item.value}`}
                data-state={isActive ? 'active' : 'inactive'}
                disabled={item.disabled}
                onClick={() => handleTabClick(item.value)}
                className={cm.cn(cm.tabsTrigger, fitted && cm.tabTriggerFitted)}
              >
                {!!item.icon && <span className={cm.tabTriggerIcon}>{item.icon as React.ReactNode}</span>}
                {item.label as React.ReactNode}
              </button>
            )
          })}
        </div>
        {!!activeItem?.content && (
          <div
            role="tabpanel"
            id={`tabpanel-${activeValue}`}
            aria-labelledby={activeValue}
            className={cm.tabsContent}
          >
            {activeItem.content as React.ReactNode}
          </div>
        )}
      </div>
    )
  },
)

Tabs.displayName = 'Tabs'
