// packages/app/frameworks/solid-ui/src/components/Avatar.tsx
/**
 * Avatar component.
 *
 * @module
 */

import { type Component, createSignal,type JSX, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { AvatarProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.jsx'

/**
 * Get initials from a name.
 * @param name - The full name to extract initials from.
 * @returns The uppercase initials string.
 */
function getInitials(name: string): string {
  return name
    .split(' ')
    .map((part) => part[0])
    .filter(Boolean)
    .slice(0, 2)
    .join('')
    .toUpperCase()
}

/**
 * Renders the Avatar component.
 * @param props - The component props.
 * @returns The rendered avatar JSX.
 */
export const Avatar: Component<AvatarProps> = (props) => {
  const [local] = splitProps(props, [
    'src',
    'alt',
    'name',
    'size',
    'rounded',
    'fallback',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const [imageError, setImageError] = createSignal(false)

  const showFallback = (): boolean => !local.src || imageError()
  const rounded = (): boolean => local.rounded ?? true

  const containerClasses = (): string =>
    cm.cn(
      cm.avatar({ size: typeof local.size === 'number' ? undefined : local.size }),
      !rounded() && cm.avatarSquare,
      local.className,
    )

  const customSize = (): { width: string; height: string } | undefined =>
    typeof local.size === 'number' ? { width: `${local.size}px`, height: `${local.size}px` } : undefined

  return (
    <div
      class={containerClasses()}
      style={{ ...local.style, ...customSize() }}
      data-testid={local.testId}
    >
      <Show
        when={!showFallback()}
        fallback={
          <div class={cm.avatarFallback}>
            <Show
              when={local.fallback}
              fallback={
                <Show
                  when={local.name}
                  fallback={renderIcon('user', cm.avatarFallbackIcon)}
                >
                  <span class={cm.avatarInitials}>{getInitials(local.name!)}</span>
                </Show>
              }
            >
              {local.fallback as JSX.Element}
            </Show>
          </div>
        }
      >
        <img
          src={local.src}
          alt={local.alt || local.name || t('ui.avatar.alt', undefined, { defaultValue: 'Avatar' })}
          class={cm.avatarImage}
          onError={() => setImageError(true)}
        />
      </Show>
    </div>
  )
}

// packages/app/frameworks/react-native-ui/src/components/Avatar.tsx
/**
 * Avatar component for React Native.
 *
 * @module
 */

import React, { useState } from 'react'
import { Image, Text, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { AvatarProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders an Avatar component.
 * @param root0 - Component props.
 * @param root0.src - Image source URL.
 * @param root0.alt - Alt text for image.
 * @param root0.name - Display name for initials.
 * @param root0.fallback - Fallback element when image unavailable.
 * @param root0.size - Avatar size.
 * @param root0.rounded - Whether rounded (circular).
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Avatar element.
 */
export const Avatar: React.FC<AvatarProps> = ({
  src,
  alt,
  name,
  fallback,
  size = 'md',
  rounded = true,
  className,
  testId,
}) => {
  const cm = getClassMap()
  const [imageError, setImageError] = useState(false)
  const namedSize = typeof size === 'string' ? size : undefined
  const classes = cm.cn(cm.avatar({ size: namedSize }), !rounded && cm.avatarSquare, className)

  const initials = name
    ? name
        .split(' ')
        .map((n) => n[0])
        .join('')
        .slice(0, 2)
        .toUpperCase()
    : undefined

  return (
    <View className={classes} testID={testId}>
      {src && !imageError ? (
        <Image
          className={cm.avatarImage}
          source={{ uri: src }}
          accessibilityLabel={
            alt || name || t('ui.avatar.alt', undefined, { defaultValue: 'Avatar' })
          }
          onError={() => setImageError(true)}
        />
      ) : initials ? (
        <Text className={cm.avatarInitials}>{initials}</Text>
      ) : fallback ? (
        <View className={cm.avatarFallbackIcon}>{fallback as React.ReactNode}</View>
      ) : (
        <Text className={cm.avatarFallback}>
          {alt?.[0]?.toUpperCase() || t('ui.avatar.fallback', undefined, { defaultValue: '?' })}
        </Text>
      )}
    </View>
  )
}
