// packages/app/frameworks/solid-ui/src/components/Layout.tsx
/**
 * Layout components.
 *
 * @module
 */

import { type Component, type JSX, splitProps } from 'solid-js'

import type { ContainerProps, FlexProps, GridProps, Size, SpacerProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Container component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Container: Component<ContainerProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'maxWidth',
    'centered',
    'paddingX',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const centered = (): boolean => local.centered ?? true

  const containerClasses = (): string =>
    cm.cn(
      cm.container({ size: (local.maxWidth ?? 'lg') as Size | '2xl' | 'full' }),
      centered() && cm.mxAuto,
      local.className,
    )

  const containerStyle = (): JSX.CSSProperties | undefined => {
    const mw = local.maxWidth ?? 'lg'
    const standardSizes = ['sm', 'md', 'lg', 'xl', '2xl', 'full']
    const customMaxWidth = !standardSizes.includes(mw) ? mw : undefined
    return customMaxWidth ? { ...local.style, 'max-width': customMaxWidth } : local.style
  }

  return (
    <div class={containerClasses()} style={containerStyle()} data-testid={local.testId}>
      {local.children as JSX.Element}
    </div>
  )
}

/**
 * Flex container component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Flex: Component<FlexProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'direction',
    'justify',
    'align',
    'wrap',
    'gap',
    'className',
    'style',
    'testId',
    'onClick',
  ])

  const cm = getClassMap()

  const flexClasses = (): string =>
    cm.cn(
      cm.flex({
        direction:
          local.direction === 'column'
            ? 'col'
            : local.direction === 'column-reverse'
              ? 'col-reverse'
              : (local.direction as 'row' | 'row-reverse' | undefined),
        align: local.align,
        justify: local.justify,
        wrap: local.wrap,
        gap:
          typeof local.gap === 'string'
            ? (local.gap as 'xs' | 'sm' | 'md' | 'lg' | 'xl')
            : undefined,
      }),
      local.className,
    )

  const gapStyle = (): { gap: string } | undefined => {
    const gap = local.gap
    if (typeof gap === 'number') return { gap: `${gap}px` }
    if (typeof gap === 'string' && !['xs', 'sm', 'md', 'lg', 'xl', 'none'].includes(gap)) {
      return { gap }
    }
    return undefined
  }

  return (
    <div
      class={flexClasses()}
      style={{ ...local.style, ...gapStyle() }}
      data-testid={local.testId}
      onClick={local.onClick as JSX.EventHandlerUnion<HTMLDivElement, MouseEvent>}
    >
      {local.children as JSX.Element}
    </div>
  )
}

/**
 * Grid container component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Grid: Component<GridProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'columns',
    'rows',
    'gap',
    'columnGap',
    'rowGap',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()

  const gridClasses = (): string =>
    cm.cn(
      cm.grid({
        cols: typeof local.columns === 'number' ? local.columns : undefined,
        gap:
          typeof local.gap === 'string'
            ? (local.gap as 'xs' | 'sm' | 'md' | 'lg' | 'xl')
            : undefined,
      }),
      typeof local.rows === 'number' && cm.gridRows(local.rows as number),
      local.className,
    )

  const gridStyle = (): JSX.CSSProperties => ({
    ...local.style,
    'grid-template-columns': typeof local.columns === 'string' ? local.columns : undefined,
    'grid-template-rows': typeof local.rows === 'string' ? local.rows : undefined,
    gap:
      typeof local.gap === 'number'
        ? `${local.gap}px`
        : typeof local.gap === 'string' &&
            !['xs', 'sm', 'md', 'lg', 'xl', 'none'].includes(local.gap)
          ? local.gap
          : undefined,
    'column-gap':
      typeof local.columnGap === 'number'
        ? `${local.columnGap}px`
        : typeof local.columnGap === 'string'
          ? local.columnGap
          : undefined,
    'row-gap':
      typeof local.rowGap === 'number'
        ? `${local.rowGap}px`
        : typeof local.rowGap === 'string'
          ? local.rowGap
          : undefined,
  })

  return (
    <div class={gridClasses()} style={gridStyle()} data-testid={local.testId}>
      {local.children as JSX.Element}
    </div>
  )
}

/**
 * Spacer component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Spacer: Component<SpacerProps> = (props) => {
  const [local] = splitProps(props, ['size', 'horizontal', 'className', 'style', 'testId'])

  const cm = getClassMap()
  const size = (): string | number => local.size ?? 'md'

  const spacerClasses = (): string => {
    const s = size()
    const isNamedSize = typeof s === 'string' && ['xs', 'sm', 'md', 'lg', 'xl'].includes(s)
    return cm.cn(
      isNamedSize
        ? cm.spacer({ size: s as Size, horizontal: local.horizontal })
        : local.horizontal
          ? cm.displayInlineBlock
          : cm.displayBlock,
      local.className,
    )
  }

  const sizeStyle = (): Record<string, string> | undefined => {
    const s = size()
    if (typeof s === 'number') {
      return local.horizontal
        ? { width: `${s}px`, height: '1px' }
        : { height: `${s}px`, width: '1px' }
    }
    if (typeof s === 'string' && !['xs', 'sm', 'md', 'lg', 'xl'].includes(s)) {
      return local.horizontal ? { width: s } : { height: s }
    }
    return undefined
  }

  return (
    <div
      class={spacerClasses()}
      style={{ ...local.style, ...sizeStyle() }}
      data-testid={local.testId}
    />
  )
}

// packages/app/frameworks/react-native-ui/src/components/Layout.tsx
/**
 * Layout components for React Native.
 *
 * @module
 */

import React from 'react'
import { View } from 'react-native'

import type { ContainerProps, FlexProps, GridProps, Size, SpacerProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders a Container component.
 * @param root0 - Component props.
 * @param root0.children - Container content.
 * @param root0.maxWidth - Maximum width constraint.
 * @param root0.centered - Whether centered.
 * @param root0.className - CSS class name override.
 * @param root0.style - Inline style object.
 * @param root0.testId - Test identifier.
 * @returns The rendered Container element.
 */
export const Container: React.FC<ContainerProps> = ({
  children,
  maxWidth = 'lg',
  centered = true,
  className,
  style,
  testId,
}) => {
  const cm = getClassMap()
  const containerClasses = cm.cn(
    cm.container({ size: maxWidth as 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'full' }),
    centered && cm.mxAuto,
    className,
  )

  return (
    <View className={containerClasses} style={style as object} testID={testId}>
      {children as React.ReactNode}
    </View>
  )
}

/**
 * Renders a Flex component.
 * @param root0 - Component props.
 * @param root0.children - Flex content.
 * @param root0.direction - Flex direction.
 * @param root0.justify - Justify content.
 * @param root0.align - Align items.
 * @param root0.wrap - Flex wrap behavior.
 * @param root0.gap - Gap between items.
 * @param root0.className - CSS class name override.
 * @param root0.style - Inline style object.
 * @param root0.testId - Test identifier.
 * @param root0.onClick - Click handler.
 * @returns The rendered Flex element.
 */
export const Flex: React.FC<FlexProps> = ({
  children,
  direction = 'row',
  justify,
  align,
  wrap,
  gap,
  className,
  style,
  testId,
  onClick,
}) => {
  const cm = getClassMap()

  const dirMap: Record<string, 'row' | 'col' | 'row-reverse' | 'col-reverse'> = {
    row: 'row',
    column: 'col',
    'row-reverse': 'row-reverse',
    'column-reverse': 'col-reverse',
  }
  const cmDirection = dirMap[direction] || 'row'

  const cmGap =
    typeof gap === 'string' && ['none', 'xs', 'sm', 'md', 'lg', 'xl'].includes(gap)
      ? (gap as 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl')
      : undefined

  const flexClasses = cm.cn(
    cm.flex({
      direction: cmDirection,
      align: align as FlexProps['align'],
      justify: justify as FlexProps['justify'],
      wrap: wrap as FlexProps['wrap'],
      gap: cmGap,
    }),
    className,
  )

  return (
    <View
      className={flexClasses}
      style={style as object}
      testID={testId}
      {...(onClick ? { onTouchEnd: onClick as unknown as () => void } : {})}
    >
      {children as React.ReactNode}
    </View>
  )
}

/**
 * Renders a Grid component.
 * @param root0 - Component props.
 * @param root0.children - Grid content.
 * @param root0.columns - Number of columns.
 * @param root0.gap - Gap between items.
 * @param root0.className - CSS class name override.
 * @param root0.style - Inline style object.
 * @param root0.testId - Test identifier.
 * @returns The rendered Grid element.
 */
export const Grid: React.FC<GridProps> = ({ children, columns, gap, className, style, testId }) => {
  const cm = getClassMap()

  const cmCols = typeof columns === 'number' ? columns : undefined
  const cmGap =
    typeof gap === 'string' && ['none', 'xs', 'sm', 'md', 'lg', 'xl'].includes(gap)
      ? (gap as 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl')
      : undefined

  const gridClasses = cm.cn(cm.grid({ cols: cmCols, gap: cmGap }), className)

  return (
    <View className={gridClasses} style={style as object} testID={testId}>
      {children as React.ReactNode}
    </View>
  )
}

/**
 * Renders a Spacer component.
 * @param root0 - Component props.
 * @param root0.size - Spacer size.
 * @param root0.horizontal - Whether horizontal.
 * @param root0.className - CSS class name override.
 * @param root0.style - Inline style object.
 * @param root0.testId - Test identifier.
 * @returns The rendered Spacer element.
 */
export const Spacer: React.FC<SpacerProps> = ({
  size = 'md',
  horizontal,
  className,
  style,
  testId,
}) => {
  const cm = getClassMap()

  const isNamedSize = typeof size === 'string' && ['xs', 'sm', 'md', 'lg', 'xl'].includes(size)

  const spacerClasses = cm.cn(
    isNamedSize ? cm.spacer({ size: size as Size, horizontal: !!horizontal }) : '',
    className,
  )

  const sizeStyle =
    typeof size === 'number' ? (horizontal ? { width: size } : { height: size }) : undefined

  return (
    <View
      className={spacerClasses}
      style={{ ...(style as object), ...sizeStyle }}
      testID={testId}
    />
  )
}
