// packages/app/frameworks/solid-ui/src/components/Pagination.tsx
/**
 * Pagination component.
 *
 * @module
 */

import { type Component, createMemo,For, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { PaginationProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.js'

/**
 * Generate pagination range with ellipsis.
 * @param currentPage - The currently active page number.
 * @param totalPages - The total number of pages.
 * @param siblings - The number of sibling pages to show around the current page.
 * @param boundaries - The number of boundary pages to always show at start and end.
 * @returns An array of page numbers and ellipsis markers.
 */
function generatePaginationRange(
  currentPage: number,
  totalPages: number,
  siblings: number,
  boundaries: number,
): (number | 'ellipsis')[] {
  const range: (number | 'ellipsis')[] = []

  // Always show first boundary pages
  for (let i = 1; i <= Math.min(boundaries, totalPages); i++) {
    range.push(i)
  }

  // Calculate sibling range
  const siblingStart = Math.max(boundaries + 1, currentPage - siblings)
  const siblingEnd = Math.min(totalPages - boundaries, currentPage + siblings)

  // Add ellipsis after boundary if needed
  if (siblingStart > boundaries + 1) {
    range.push('ellipsis')
  }

  // Add sibling pages
  for (let i = siblingStart; i <= siblingEnd; i++) {
    if (!range.includes(i)) {
      range.push(i)
    }
  }

  // Add ellipsis before end boundary if needed
  if (siblingEnd < totalPages - boundaries) {
    range.push('ellipsis')
  }

  // Always show last boundary pages
  for (let i = Math.max(totalPages - boundaries + 1, boundaries + 1); i <= totalPages; i++) {
    if (!range.includes(i)) {
      range.push(i)
    }
  }

  return range
}

/**
 * Pagination component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Pagination: Component<PaginationProps> = (props) => {
  const [local] = splitProps(props, [
    'page',
    'totalPages',
    'onChange',
    'siblings',
    'boundaries',
    'size',
    'showFirstLast',
    'showPrevNext',
    'labels',
    'className',
    'style',
    'testId',
    'disabled',
  ])

  const cm = getClassMap()
  const siblings = (): number => local.siblings ?? 1
  const boundaries = (): number => local.boundaries ?? 1
  const showFirstLast = (): boolean => local.showFirstLast ?? false
  const showPrevNext = (): boolean => local.showPrevNext ?? true

  const range = createMemo(() =>
    generatePaginationRange(local.page, local.totalPages, siblings(), boundaries()),
  )

  const handlePageChange = (newPage: number): void => {
    if (newPage >= 1 && newPage <= local.totalPages && newPage !== local.page && !local.disabled) {
      local.onChange(newPage)
    }
  }

  const buttonClasses = (isActive: boolean): string =>
    cm.cn(
      cm.pagination({
        active: isActive,
        size: local.size,
      }),
      cm.paginationInteractive,
    )

  return (
    <nav
      role="navigation"
      aria-label={local.labels?.nav ?? t('ui.pagination.nav', undefined, { defaultValue: 'Pagination' })}
      class={cm.cn(cm.paginationRoot, local.className)}
      style={local.style}
      data-testid={local.testId}
    >
      <ul class={cm.paginationContent}>
        {/* First page button */}
        <Show when={showFirstLast()}>
          <li>
            <button
              type="button"
              class={buttonClasses(false)}
              onClick={() => handlePageChange(1)}
              disabled={local.page === 1 || local.disabled}
              aria-label={local.labels?.first ?? t('ui.pagination.first', undefined, { defaultValue: 'Go to first page' })}
            >
              {renderIcon('chevrons-left', cm.iconSm)}
            </button>
          </li>
        </Show>

        {/* Previous page button */}
        <Show when={showPrevNext()}>
          <li>
            <button
              type="button"
              class={buttonClasses(false)}
              onClick={() => handlePageChange(local.page - 1)}
              disabled={local.page === 1 || local.disabled}
              aria-label={local.labels?.previous ?? t('ui.pagination.previous', undefined, { defaultValue: 'Go to previous page' })}
            >
              {renderIcon('chevron-left', cm.iconSm)}
            </button>
          </li>
        </Show>

        {/* Page numbers */}
        <For each={range()}>
          {(item, _index) => (
            <Show
              when={item !== 'ellipsis'}
              fallback={
                <li>
                  <span class={cm.paginationEllipsis} aria-hidden="true">
                    {renderIcon('ellipsis-horizontal', cm.iconSm)}
                  </span>
                </li>
              }
            >
              <li>
                <button
                  type="button"
                  class={buttonClasses((item as number) === local.page)}
                  onClick={() => handlePageChange(item as number)}
                  disabled={local.disabled}
                  aria-label={local.labels?.goToPage?.(item as number) ?? t('ui.pagination.goToPage', { page: item as number }, { defaultValue: 'Go to page {{page}}' })}
                  aria-current={(item as number) === local.page ? 'page' : undefined}
                >
                  {item as number}
                </button>
              </li>
            </Show>
          )}
        </For>

        {/* Next page button */}
        <Show when={showPrevNext()}>
          <li>
            <button
              type="button"
              class={buttonClasses(false)}
              onClick={() => handlePageChange(local.page + 1)}
              disabled={local.page === local.totalPages || local.disabled}
              aria-label={local.labels?.next ?? t('ui.pagination.next', undefined, { defaultValue: 'Go to next page' })}
            >
              {renderIcon('chevron-right', cm.iconSm)}
            </button>
          </li>
        </Show>

        {/* Last page button */}
        <Show when={showFirstLast()}>
          <li>
            <button
              type="button"
              class={buttonClasses(false)}
              onClick={() => handlePageChange(local.totalPages)}
              disabled={local.page === local.totalPages || local.disabled}
              aria-label={local.labels?.last ?? t('ui.pagination.last', undefined, { defaultValue: 'Go to last page' })}
            >
              {renderIcon('chevrons-right', cm.iconSm)}
            </button>
          </li>
        </Show>
      </ul>
    </nav>
  )
}

// packages/app/frameworks/react-native-ui/src/components/Pagination.tsx
/**
 * Pagination component for React Native.
 *
 * @module
 */

import React from 'react'
import { Pressable, Text, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { PaginationProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders a Pagination component.
 * @param root0 - Component props.
 * @param root0.page - Current page number.
 * @param root0.totalPages - Total number of pages.
 * @param root0.onChange - Page change handler.
 * @param root0.siblings - Visible sibling pages.
 * @param root0.boundaries - Boundary page count.
 * @param root0.size - Pagination size.
 * @param root0.showFirstLast - Show first/last buttons.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Pagination element.
 */
export const Pagination: React.FC<PaginationProps> = ({
  page,
  totalPages,
  onChange,
  siblings = 1,
  boundaries = 1,
  size = 'md',
  showFirstLast,
  className,
  testId,
}) => {
  const cm = getClassMap()

  const range = (start: number, end: number): number[] =>
    Array.from({ length: end - start + 1 }, (_, i) => start + i)

  const buildPaginationRange = (): (number | 'ellipsis')[] => {
    const total = totalPages
    const sibling = siblings
    const boundary = boundaries

    const leftBoundary = range(1, Math.min(boundary, total))
    const rightBoundary = range(Math.max(total - boundary + 1, boundary + 1), total)

    const siblingsStart = Math.max(
      Math.min(page - sibling, total - boundary - sibling * 2 - 1),
      boundary + 2,
    )
    const siblingsEnd = Math.min(
      Math.max(page + sibling, boundary + sibling * 2 + 2),
      total - boundary - 1,
    )

    const items: (number | 'ellipsis')[] = []

    items.push(...leftBoundary)
    if (siblingsStart > boundary + 2) items.push('ellipsis')
    else if (boundary + 1 < siblingsStart) items.push(boundary + 1)

    items.push(...range(siblingsStart, siblingsEnd))

    if (siblingsEnd < total - boundary - 1) items.push('ellipsis')
    else if (total - boundary > siblingsEnd) items.push(total - boundary)

    items.push(...rightBoundary)
    return [...new Set(items)]
  }

  const pages = buildPaginationRange()

  return (
    <View
      className={cm.cn(cm.paginationRoot, className)}
      testID={testId}
      accessibilityRole="toolbar"
      accessibilityLabel={t('ui.pagination.nav', undefined, { defaultValue: 'Pagination' })}
    >
      <View className={cm.paginationContent}>
        {showFirstLast && (
          <Pressable
            className={cm.paginationPrevious}
            onPress={() => onChange?.(1)}
            disabled={page <= 1}
            accessibilityLabel={t('ui.pagination.first', undefined, { defaultValue: 'First' })}
          >
            <Text>{t('ui.icon.chevronsLeft', undefined, { defaultValue: '«' })}</Text>
          </Pressable>
        )}
        <Pressable
          className={cm.paginationPrevious}
          onPress={() => onChange?.(page - 1)}
          disabled={page <= 1}
          accessibilityLabel={t('ui.pagination.previous', undefined, { defaultValue: 'Previous' })}
        >
          <Text>{t('ui.icon.chevronLeft', undefined, { defaultValue: '‹' })}</Text>
        </Pressable>

        {pages.map((item, i) =>
          item === 'ellipsis' ? (
            <View key={`ellipsis-${i}`} className={cm.paginationEllipsis}>
              <Text>{t('ui.icon.ellipsis', undefined, { defaultValue: '…' })}</Text>
            </View>
          ) : (
            <Pressable
              key={item}
              className={cm.cn(cm.paginationLink, cm.pagination({ active: item === page, size }))}
              onPress={() => onChange?.(item)}
              accessibilityRole="button"
              accessibilityState={{ selected: item === page }}
              accessibilityLabel={t(
                'ui.pagination.goToPage',
                { page: String(item) },
                { defaultValue: `Page ${item}` },
              )}
            >
              <Text>{item}</Text>
            </Pressable>
          ),
        )}

        <Pressable
          className={cm.paginationNext}
          onPress={() => onChange?.(page + 1)}
          disabled={page >= totalPages}
          accessibilityLabel={t('ui.pagination.next', undefined, { defaultValue: 'Next' })}
        >
          <Text>{t('ui.icon.chevronRight', undefined, { defaultValue: '›' })}</Text>
        </Pressable>
        {showFirstLast && (
          <Pressable
            className={cm.paginationNext}
            onPress={() => onChange?.(totalPages)}
            disabled={page >= totalPages}
            accessibilityLabel={t('ui.pagination.last', undefined, { defaultValue: 'Last' })}
          >
            <Text>{t('ui.icon.chevronsRight', undefined, { defaultValue: '»' })}</Text>
          </Pressable>
        )}
      </View>
    </View>
  )
}
