// packages/app/frameworks/solid-ui/src/components/Progress.tsx
/**
 * Progress component.
 *
 * @module
 */

import { type Component, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { BaseProps, ColorVariant, Size } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Props for the Progress component.
 */
export interface ProgressProps extends BaseProps {
  /**
   * Progress value (0-100).
   */
  value: number

  /**
   * Maximum value.
   */
  max?: number

  /**
   * Progress size.
   */
  size?: Size

  /**
   * Progress color.
   */
  color?: ColorVariant

  /**
   * Whether to show the value label.
   */
  showValue?: boolean

  /**
   * Accessible label.
   */
  label?: string

  /**
   * Whether the progress is indeterminate.
   */
  indeterminate?: boolean
}

/**
 * Progress component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Progress: Component<ProgressProps> = (props) => {
  const [local] = splitProps(props, [
    'value',
    'max',
    'size',
    'color',
    'showValue',
    'label',
    'indeterminate',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const max = (): number => local.max ?? 100
  const percentage = (): number => Math.min(Math.max((local.value / max()) * 100, 0), 100)

  return (
    <div class={cm.cn(cm.progressWrapper, local.className)} style={local.style} data-testid={local.testId}>
      <Show when={local.label || local.showValue}>
        <div class={cm.progressLabelContainer}>
          <Show when={local.label}>
            <span class={cm.progressLabelText}>{local.label}</span>
          </Show>
          <Show when={local.showValue}>
            <span class={cm.progressLabelText}>{Math.round(percentage())}%</span>
          </Show>
        </div>
      </Show>
      <div
        class={cm.cn(cm.progress(), cm.progressHeight(local.size || 'md'))}
        role="progressbar"
        aria-valuenow={local.indeterminate ? undefined : local.value}
        aria-valuemin={0}
        aria-valuemax={max()}
        aria-label={local.label ?? t('ui.progress.label', undefined, { defaultValue: 'Progress' })}
      >
        <div
          class={cm.cn(
            cm.progressBar(),
            cm.progressColor(local.color || 'primary'),
            local.indeterminate && cm.progressIndeterminate,
          )}
          style={
            local.indeterminate ? undefined : { transform: `translateX(-${100 - percentage()}%)` }
          }
        />
      </div>
    </div>
  )
}

// packages/app/frameworks/react-native-ui/src/components/Progress.tsx
/**
 * Progress component for React Native.
 *
 * @module
 */

import React from 'react'
import { Text, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { BaseProps, ColorVariant, Size } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/** Local progress props (not exported from `@molecule/app-ui`). */
interface ProgressProps extends BaseProps {
  value?: number
  max?: number
  label?: unknown
  showValue?: boolean
  color?: ColorVariant
  size?: Size
  indeterminate?: boolean
}

/**
 * Renders a Progress component.
 * @param root0 - Component props.
 * @param root0.value - Current progress value.
 * @param root0.max - Maximum progress value.
 * @param root0.label - Progress label text.
 * @param root0.showValue - Whether to show value.
 * @param root0.color - Progress bar color.
 * @param root0.size - Progress bar size.
 * @param root0.indeterminate - Whether indeterminate.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Progress element.
 */
export const Progress: React.FC<ProgressProps> = ({
  value = 0,
  max = 100,
  label,
  showValue,
  color = 'primary',
  size = 'md',
  indeterminate,
  className,
  testId,
}) => {
  const cm = getClassMap()
  const percentage = Math.min(Math.max((value / max) * 100, 0), 100)

  return (
    <View className={cm.cn(cm.progressWrapper, className)} testID={testId}>
      {(label || showValue) && (
        <View className={cm.progressLabelContainer}>
          {!!label && <Text className={cm.progressLabelText}>{label as React.ReactNode}</Text>}
          {showValue && (
            <Text className={cm.progressLabelText}>
              {t(
                'ui.progress.value',
                { value: String(Math.round(percentage)) },
                { defaultValue: '{{value}}%' },
              )}
            </Text>
          )}
        </View>
      )}
      <View
        className={cm.cn(cm.progress(), cm.progressHeight(size))}
        accessibilityRole="progressbar"
        accessibilityLabel={
          typeof label === 'string'
            ? label
            : t('ui.progress.label', undefined, { defaultValue: 'Progress' })
        }
        accessibilityValue={{
          min: 0,
          max,
          now: indeterminate ? undefined : value,
        }}
      >
        <View
          className={cm.cn(
            cm.progressBar(),
            cm.progressColor(color),
            indeterminate && cm.progressIndeterminate,
          )}
          style={indeterminate ? { width: '50%' } : { width: `${percentage}%` }}
        />
      </View>
    </View>
  )
}
