// packages/app/frameworks/solid-ui/src/components/RadioGroup.tsx
/**
 * RadioGroup component.
 *
 * @module
 */

import { type Component, For, type JSX, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { RadioGroupProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the RadioGroup component.
 * @param props - The component props.
 * @returns The rendered radio group JSX.
 */
export const RadioGroup: Component<RadioGroupProps<string>> = (props) => {
  const [local] = splitProps(props, [
    'options',
    'value',
    'onChange',
    'size',
    'label',
    'direction',
    'error',
    'className',
    'style',
    'testId',
    'disabled',
  ])

  const cm = getClassMap()
  const direction = (): 'horizontal' | 'vertical' => local.direction || 'vertical'

  const handleChange = (optionValue: string): void => {
    local.onChange?.(optionValue)
  }

  return (
    <div
      class={local.className}
      style={local.style}
      data-testid={local.testId}
      role="radiogroup"
      aria-label={
        local.label ?? t('ui.radioGroup.label', undefined, { defaultValue: 'Radio group' })
      }
    >
      <Show when={local.label}>
        <div class={cm.cn(cm.label({}), cm.radioGroupLabel)}>{local.label}</div>
      </Show>
      <div class={cm.radioGroupLayout(direction())}>
        <For each={local.options}>
          {(option) => {
            const isChecked = (): boolean => local.value === option.value
            const isDisabled = (): boolean | undefined => local.disabled || option.disabled

            return (
              <label class={cm.cn(cm.controlLabel, isDisabled() && cm.controlDisabled)}>
                <input
                  type="radio"
                  name={local.label}
                  value={option.value}
                  checked={isChecked()}
                  disabled={isDisabled()}
                  onChange={() => handleChange(option.value)}
                  data-state={isChecked() ? 'checked' : 'unchecked'}
                  class={cm.cn(cm.radio({ error: !!local.error }), cm.cursorPointer)}
                />
                <span class={cm.controlText}>{option.label as JSX.Element}</span>
              </label>
            )
          }}
        </For>
      </div>
      <Show when={local.error}>
        <p class={cm.cn(cm.formError, cm.sp('mt', 1))}>{local.error}</p>
      </Show>
    </div>
  )
}

// packages/app/frameworks/react-native-ui/src/components/RadioGroup.tsx
/**
 * RadioGroup component for React Native.
 *
 * @module
 */

import React from 'react'
import { Pressable, Text, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { RadioGroupProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders a RadioGroup component.
 * @param root0 - Component props.
 * @param root0.label - Group label text.
 * @param root0.options - Radio options array.
 * @param root0.value - Selected value.
 * @param root0.onChange - Change handler.
 * @param root0.direction - Layout direction.
 * @param root0.error - Error message.
 * @param root0.disabled - Whether disabled.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered RadioGroup element.
 */
export const RadioGroup: React.FC<RadioGroupProps> = ({
  label,
  options = [],
  value,
  onChange,
  direction = 'vertical',
  error,
  disabled,
  className,
  testId,
}) => {
  const cm = getClassMap()
  const layoutClasses = cm.radioGroupLayout(direction)

  return (
    <View
      className={className}
      testID={testId}
      accessibilityRole="radiogroup"
      accessibilityLabel={
        typeof label === 'string'
          ? label
          : t('ui.radioGroup.label', undefined, { defaultValue: 'Radio group' })
      }
    >
      {!!label && <Text className={cm.radioGroupLabel}>{label as React.ReactNode}</Text>}
      <View className={layoutClasses}>
        {options.map((option) => {
          const optValue = typeof option === 'string' ? option : option.value
          const optLabel = typeof option === 'string' ? option : option.label
          const optDisabled = disabled || (typeof option === 'object' && option.disabled)
          const isSelected = optValue === value

          return (
            <Pressable
              key={optValue}
              className={cm.controlLabel}
              onPress={() => {
                if (!optDisabled && onChange) {
                  onChange(optValue)
                }
              }}
              disabled={!!optDisabled}
              accessibilityRole="radio"
              accessibilityState={{ selected: isSelected, disabled: !!optDisabled }}
            >
              <View className={cm.radio({ error: !!error })}>
                {isSelected && <View className={cm.roundedFull} />}
              </View>
              <Text className={cm.cn(cm.controlText, optDisabled && cm.controlDisabled)}>
                {optLabel as React.ReactNode}
              </Text>
            </Pressable>
          )
        })}
      </View>
      {!!error && typeof error === 'string' && <Text className={cm.formError}>{error}</Text>}
    </View>
  )
}
