// packages/app/frameworks/solid-ui/src/components/Separator.tsx
/**
 * Separator component.
 *
 * @module
 */

import { type Component, splitProps } from 'solid-js'

import type { SeparatorProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the Separator component.
 * @param props - The component props.
 * @returns The rendered separator JSX.
 */
export const Separator: Component<SeparatorProps> = (props) => {
  const [local] = splitProps(props, [
    'orientation',
    'decorative',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const orientation = (): 'horizontal' | 'vertical' => local.orientation || 'horizontal'
  const decorative = (): boolean => local.decorative ?? true

  const separatorClasses = (): string => cm.cn(cm.separator({ orientation: orientation() }), local.className)

  return (
    <div
      role={decorative() ? 'none' : 'separator'}
      aria-orientation={decorative() ? undefined : orientation()}
      class={separatorClasses()}
      style={local.style}
      data-testid={local.testId}
    />
  )
}

// packages/app/frameworks/react-native-ui/src/components/Separator.tsx
/**
 * Separator component for React Native.
 *
 * @module
 */

import React from 'react'
import { View } from 'react-native'

import type { SeparatorProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders a Separator component.
 * @param root0 - Component props.
 * @param root0.orientation - Horizontal or vertical.
 * @param root0.decorative - Whether purely decorative.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Separator element.
 */
export const Separator: React.FC<SeparatorProps> = ({
  orientation = 'horizontal',
  decorative = true,
  className,
  testId,
}) => {
  const cm = getClassMap()
  const classes = cm.cn(cm.separator({ orientation }), className)

  return (
    <View
      className={classes}
      testID={testId}
      accessibilityRole={decorative ? 'none' : ('separator' as never)}
    />
  )
}
