// packages/app/frameworks/solid-ui/src/components/Toast.tsx
/**
 * Toast component.
 *
 * @module
 */

import {
  type Component,
  createContext,
  createEffect,
  createSignal,
  For,
  type JSX,
  onCleanup,
  Show,
  splitProps,
  useContext,
} from 'solid-js'
import { Portal } from 'solid-js/web'

import { t } from '@molecule/app-i18n'
import type { ColorVariant,ToastProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.jsx'

const statusVariantMap: Record<ColorVariant, 'default' | 'success' | 'warning' | 'error' | 'info'> =
  {
    primary: 'default',
    secondary: 'default',
    success: 'success',
    warning: 'warning',
    error: 'error',
    info: 'info',
  }

const statusIconMap: Record<string, string> = {
  info: 'info-circle',
  success: 'check-circle',
  warning: 'exclamation-triangle',
  error: 'x-circle',
}


/**
 * Single Toast component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Toast: Component<ToastProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'title',
    'description',
    'status',
    'duration',
    'dismissible',
    'closeLabel',
    'onDismiss',
    'position',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const [isVisible, setIsVisible] = createSignal(true)
  const variant = (): 'default' | 'success' | 'warning' | 'error' | 'info' => statusVariantMap[local.status || 'info'] || 'default'
  const iconName = (): string | undefined => statusIconMap[variant()]
  const duration = (): number => local.duration ?? 5000
  const dismissible = (): boolean => local.dismissible ?? true

  createEffect(() => {
    if (duration() > 0) {
      const timer = setTimeout(() => {
        setIsVisible(false)
        local.onDismiss?.()
      }, duration())
      onCleanup(() => clearTimeout(timer))
    }
  })

  const handleDismiss = (): void => {
    setIsVisible(false)
    local.onDismiss?.()
  }

  return (
    <Show when={isVisible()}>
      <div
        role="alert"
        data-state="open"
        class={cm.cn(cm.toast({ variant: variant() }), local.className)}
        style={local.style}
        data-testid={local.testId}
      >
        <Show when={iconName()}>
          <span class={cm.toastIconWrapper}>
            {renderIcon(iconName()!, cm.iconMd)}
          </span>
        </Show>
        <div class={cm.toastContentWrapper}>
          <Show when={local.title}>
            <div class={cm.toastTitle}>{local.title}</div>
          </Show>
          <Show when={!!(local.description || local.children)}>
            <div class={cm.toastDescription}>
              {(local.description as JSX.Element) || (local.children as JSX.Element)}
            </div>
          </Show>
        </div>
        <Show when={dismissible()}>
          <button
            type="button"
            onClick={handleDismiss}
            class={cm.toastClose}
            aria-label={local.closeLabel ?? t('ui.toast.close', undefined, { defaultValue: 'Close' })}
          >
            {renderIcon('x-mark', cm.iconSm)}
          </button>
        </Show>
      </div>
    </Show>
  )
}

/**
 * Toast container for positioning toasts.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const ToastContainer: Component<{
  children?: JSX.Element
  position?: ToastProps['position']
  class?: string
}> = (props) => {
  const cm = getClassMap()
  const position = (): NonNullable<ToastProps['position']> => props.position || 'bottom-right'

  return (
    <Portal>
      <div
        class={cm.cn(
          cm.toastContainer({ position: position() }),
          props.class,
        )}
      >
        {props.children}
      </div>
    </Portal>
  )
}

/**
 * Toast context for managing toasts globally.
 */
interface ToastContextValue {
  toasts: () => (ToastProps & { id: string })[]
  addToast: (toast: Omit<ToastProps, 'onDismiss'>) => string
  removeToast: (id: string) => void
}

const ToastContext = createContext<ToastContextValue>()

/**
 * Hook to access the toast context for adding and removing toasts.
 * @returns The toast context value with toast management methods.
 */
export const useToast = (): ToastContextValue => {
  const context = useContext(ToastContext)
  if (!context) {
    throw new Error(t('solid.error.useToastOutsideProvider', undefined, { defaultValue: 'useToast must be used within a ToastProvider' }))
  }
  return context
}

let toastCounter = 0

/**
 * Provider component that manages global toast state.
 * @param props - The component props.
 * @returns The rendered provider with toast container.
 */
export const ToastProvider: Component<{
  children: JSX.Element
  position?: ToastProps['position']
}> = (props) => {
  const [toasts, setToasts] = createSignal<(ToastProps & { id: string })[]>([])
  const position = (): NonNullable<ToastProps['position']> => props.position || 'bottom-right'

  const addToast = (toast: Omit<ToastProps, 'onDismiss'>): string => {
    const id = `toast-${++toastCounter}`
    setToasts((prev) => [...prev, { ...toast, id }])
    return id
  }

  const removeToast = (id: string): void => {
    setToasts((prev) => prev.filter((t) => t.id !== id))
  }

  return (
    <ToastContext.Provider value={{ toasts, addToast, removeToast }}>
      {props.children}
      <ToastContainer position={position()}>
        <For each={toasts()}>
          {(toast) => <Toast {...toast} onDismiss={() => removeToast(toast.id)} />}
        </For>
      </ToastContainer>
    </ToastContext.Provider>
  )
}

// packages/app/frameworks/react-native-ui/src/components/Toast.tsx
/**
 * Toast notification components for React Native.
 *
 * @module
 */

import React, { createContext, useCallback, useContext, useEffect, useRef, useState } from 'react'
import { Animated, Pressable, Text, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { ToastProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders a Toast component.
 * @param root0 - Component props.
 * @param root0.title - Toast title text.
 * @param root0.description - Toast description text.
 * @param root0.status - Status type.
 * @param root0.duration - Auto-dismiss duration (ms).
 * @param root0.dismissible - Whether dismissible.
 * @param root0.onDismiss - Dismiss handler.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Toast element.
 */
export const Toast: React.FC<ToastProps> = ({
  title,
  description,
  status,
  duration = 5000,
  dismissible = true,
  onDismiss,
  className,
  testId,
}) => {
  const cm = getClassMap()
  const classes = cm.cn(
    cm.toast({
      variant: (status || 'default') as 'default' | 'success' | 'warning' | 'error' | 'info',
    }),
    className,
  )
  const opacity = useRef(new Animated.Value(1)).current

  useEffect(() => {
    if (duration > 0) {
      const timer = setTimeout(() => {
        Animated.timing(opacity, {
          toValue: 0,
          duration: 300,
          useNativeDriver: true,
        }).start(() => onDismiss?.())
      }, duration)
      return () => clearTimeout(timer)
    }
    return undefined
  }, [duration, onDismiss, opacity])

  return (
    <Animated.View className={classes} style={{ opacity }} testID={testId}>
      <View className={cm.toastContentWrapper}>
        {!!title && <Text className={cm.toastTitle}>{title as React.ReactNode}</Text>}
        {!!description && (
          <Text className={cm.toastDescription}>{description as React.ReactNode}</Text>
        )}
      </View>
      {dismissible && (
        <Pressable
          className={cm.toastClose}
          onPress={onDismiss}
          accessibilityLabel={t('ui.toast.dismiss', undefined, { defaultValue: 'Dismiss' })}
          accessibilityRole="button"
        >
          <Text>{t('ui.icon.close', undefined, { defaultValue: '✕' })}</Text>
        </Pressable>
      )}
    </Animated.View>
  )
}

/**
 * Renders a ToastContainer component.
 * @param root0 - Component props.
 * @param root0.children - Toast elements.
 * @param root0.position - Screen position.
 * @returns The rendered ToastContainer element.
 */
export const ToastContainer: React.FC<{
  children: React.ReactNode
  position?: 'top' | 'top-right' | 'top-left' | 'bottom' | 'bottom-right' | 'bottom-left'
}> = ({ children, position = 'bottom-right' }) => {
  const cm = getClassMap()
  return <View className={cm.toastContainer({ position })}>{children}</View>
}

// ---- Toast context ----

interface ToastItem {
  id: number
  props: ToastProps
}

interface ToastContextValue {
  toast: (props: Omit<ToastProps, 'onDismiss'>) => number
  dismiss: (id: number) => void
}

const ToastContext = createContext<ToastContextValue | null>(null)

let toastCounter = 0

/**
 * Renders a ToastProvider component.
 * @param root0 - Component props.
 * @param root0.children - App content.
 * @param root0.position - Toast position.
 * @returns The rendered ToastProvider element.
 */
export const ToastProvider: React.FC<{
  children: React.ReactNode
  position?: 'top' | 'top-right' | 'top-left' | 'bottom' | 'bottom-right' | 'bottom-left'
}> = ({ children, position = 'bottom-right' }) => {
  const [toasts, setToasts] = useState<ToastItem[]>([])

  const toast = useCallback((props: Omit<ToastProps, 'onDismiss'>) => {
    const id = ++toastCounter
    setToasts((prev) => [...prev, { id, props: props as ToastProps }])
    return id
  }, [])

  const dismiss = useCallback((id: number) => {
    setToasts((prev) => prev.filter((t) => t.id !== id))
  }, [])

  return (
    <ToastContext.Provider value={{ toast, dismiss }}>
      {children}
      <ToastContainer position={position}>
        {toasts.map((item) => (
          <Toast key={item.id} {...item.props} onDismiss={() => dismiss(item.id)} />
        ))}
      </ToastContainer>
    </ToastContext.Provider>
  )
}

/**
 * Hook for toast notifications.
 * @returns The toast context value.
 */
export function useToast(): ToastContextValue {
  const context = useContext(ToastContext)
  if (!context) {
    throw new Error(
      t('ui.toast.error.noProvider', undefined, {
        defaultValue: 'useToast must be used within a ToastProvider',
      }),
    )
  }
  return context
}
