// packages/app/frameworks/react-native-ui/src/components/Accordion.tsx
/**
 * Accordion component for React Native.
 *
 * @module
 */

import React, { createContext, useCallback, useState } from 'react'
import { Pressable, Text, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { AccordionProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

interface AccordionContextValue {
  openItems: string[]
  toggle: (value: string) => void
}

const AccordionContext = createContext<AccordionContextValue>({
  openItems: [],
  toggle: () => {},
})

/**
 * Renders an Accordion component.
 * @param root0 - Component props.
 * @param root0.items - Accordion items array.
 * @param root0.multiple - Whether multiple items can be open.
 * @param root0.defaultValue - Initial open value.
 * @param root0.value - Controlled open value.
 * @param root0.onChange - Change handler.
 * @param root0.collapsible - Whether items collapse.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Accordion element.
 */
export const Accordion: React.FC<AccordionProps> = ({
  items = [],
  multiple = false,
  defaultValue,
  value: controlledValue,
  onChange,
  collapsible = true,
  className,
  testId,
}) => {
  const cm = getClassMap()

  const normalize = (v: string | string[] | undefined): string[] => {
    if (!v) return []
    return Array.isArray(v) ? v : [v]
  }

  const [uncontrolledOpen, setUncontrolledOpen] = useState<string[]>(normalize(defaultValue))
  const openItems = controlledValue !== undefined ? normalize(controlledValue) : uncontrolledOpen

  const toggle = useCallback(
    (itemValue: string) => {
      let next: string[]
      if (openItems.includes(itemValue)) {
        if (!collapsible && openItems.length === 1) return
        next = openItems.filter((v) => v !== itemValue)
      } else {
        next = !multiple ? [itemValue] : [...openItems, itemValue]
      }

      if (controlledValue === undefined) {
        setUncontrolledOpen(next)
      }
      onChange?.(!multiple ? next[0] || '' : next)
    },
    [openItems, multiple, collapsible, controlledValue, onChange],
  )

  return (
    <AccordionContext.Provider value={{ openItems, toggle }}>
      <View className={cm.cn(cm.accordionRoot, className)} testID={testId}>
        {items.map((item) => {
          const isOpen = openItems.includes(item.value)
          return (
            <View key={item.value} className={cm.accordionItem}>
              <Pressable
                className={cm.cn(cm.accordionTriggerBase, cm.accordion())}
                onPress={() => toggle(item.value)}
                accessibilityRole="button"
                accessibilityState={{ expanded: isOpen }}
              >
                <Text>{item.header as React.ReactNode}</Text>
                <Text className={cm.accordionChevron}>
                  {isOpen
                    ? t('ui.icon.chevronUp', undefined, { defaultValue: '▲' })
                    : t('ui.icon.chevronDown', undefined, { defaultValue: '▼' })}
                </Text>
              </Pressable>
              {isOpen && (
                <View className={cm.accordionContent}>
                  <View className={cm.accordionContentInner}>
                    {item.content as React.ReactNode}
                  </View>
                </View>
              )}
            </View>
          )
        })}
      </View>
    </AccordionContext.Provider>
  )
}

// packages/app/frameworks/solid-ui/src/components/Accordion.tsx
/**
 * Accordion component.
 *
 * @module
 */

import {
  type Component,
  createContext,
  createSignal,
  createUniqueId,
  For,
  type JSX,
  splitProps,
  useContext,
} from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { AccordionItem as AccordionItemType,AccordionProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.js'

/**
 * Context for accordion state.
 */
interface AccordionContextValue {
  expandedItems: () => string[]
  toggleItem: (value: string) => void
  multiple: boolean
}

const AccordionContext = createContext<AccordionContextValue>()

const useAccordionContext = (): AccordionContextValue => {
  const context = useContext(AccordionContext)
  if (!context) {
    throw new Error(t('solid.error.useAccordionOutsideProvider', undefined, { defaultValue: 'Accordion components must be used within an Accordion' }))
  }
  return context
}

/**
 * Renders a single accordion item component.
 * @param props - The component props.
 * @returns The rendered accordion item JSX.
 */
const AccordionItemComponent: Component<{
  item: AccordionItemType<string>
  class?: string
}> = (props) => {
  const { expandedItems, toggleItem } = useAccordionContext()
  const cm = getClassMap()
  const isExpanded = (): boolean => expandedItems().includes(props.item.value)
  const contentId = createUniqueId()
  const triggerId = createUniqueId()

  return (
    <div
      class={cm.cn(cm.accordionItem, props.class)}
      data-state={isExpanded() ? 'open' : 'closed'}
    >
      <button
        id={triggerId}
        type="button"
        class={cm.cn(cm.accordion({}), cm.accordionTriggerBase)}
        onClick={() => !props.item.disabled && toggleItem(props.item.value)}
        aria-expanded={isExpanded()}
        aria-controls={contentId}
        data-state={isExpanded() ? 'open' : 'closed'}
        disabled={props.item.disabled}
      >
        {props.item.header as JSX.Element}
        {renderIcon('chevron-down', cm.accordionChevron)}
      </button>
      <div
        id={contentId}
        role="region"
        aria-labelledby={triggerId}
        data-state={isExpanded() ? 'open' : 'closed'}
        class={cm.accordionContent}
        style={{
          display: isExpanded() ? 'block' : 'none',
        }}
      >
        <div class={cm.accordionContentInner}>{props.item.content as JSX.Element}</div>
      </div>
    </div>
  )
}

/**
 * Renders the Accordion component.
 * @param props - The component props.
 * @returns The rendered accordion JSX.
 */
export const Accordion: Component<AccordionProps<string>> = (props) => {
  const [local] = splitProps(props, [
    'items',
    'value',
    'defaultValue',
    'onChange',
    'multiple',
    'collapsible',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const multiple = (): boolean => local.multiple ?? false
  const collapsible = (): boolean => local.collapsible ?? true

  // Normalize value to array
  const normalizeValue = (v: string | string[] | undefined): string[] => {
    if (v === undefined) return []
    return Array.isArray(v) ? v : [v]
  }

  const [internalExpanded, setInternalExpanded] = createSignal<string[]>(
    normalizeValue(local.defaultValue),
  )

  // Use controlled value if provided, otherwise use internal state
  const expandedItems = (): string[] =>
    local.value !== undefined ? normalizeValue(local.value) : internalExpanded()

  const toggleItem = (itemValue: string): void => {
    const current = expandedItems()
    let newExpanded: string[]

    if (current.includes(itemValue)) {
      // Collapsing
      if (!collapsible() && current.length === 1) {
        // Can't collapse if not collapsible and it's the only expanded item
        return
      }
      newExpanded = current.filter((v) => v !== itemValue)
    } else {
      // Expanding
      if (multiple()) {
        newExpanded = [...current, itemValue]
      } else {
        newExpanded = [itemValue]
      }
    }

    if (local.value === undefined) {
      setInternalExpanded(newExpanded)
    }

    // Call onChange with appropriate type
    if (local.onChange) {
      if (multiple()) {
        local.onChange(newExpanded as string & string[])
      } else {
        local.onChange((newExpanded[0] || '') as string & string[])
      }
    }
  }

  return (
    <AccordionContext.Provider value={{ expandedItems, toggleItem, multiple: multiple() }}>
      <div class={cm.cn(cm.accordionRoot, local.className)} style={local.style} data-testid={local.testId}>
        <For each={local.items}>
          {(item) => <AccordionItemComponent item={item} />}
        </For>
      </div>
    </AccordionContext.Provider>
  )
}
