// packages/app/frameworks/react-native-ui/src/components/Alert.tsx
/**
 * Alert component for React Native.
 *
 * @module
 */

import React from 'react'
import { Pressable, Text, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { AlertProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders an Alert component.
 * @param root0 - Component props.
 * @param root0.children - Alert body content.
 * @param root0.title - Alert title text.
 * @param root0.variant - Visual variant.
 * @param root0.status - Status type.
 * @param root0.icon - Leading icon element.
 * @param root0.dismissible - Whether dismissible.
 * @param root0.onDismiss - Dismiss handler.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Alert element.
 */
export const Alert: React.FC<AlertProps> = ({
  children,
  title,
  variant: _variant = 'subtle',
  status,
  icon,
  dismissible,
  onDismiss,
  className,
  testId,
}) => {
  const cm = getClassMap()
  const classes = cm.cn(
    cm.alert({
      variant: (status || 'default') as 'default' | 'info' | 'success' | 'warning' | 'error',
    }),
    className,
  )

  return (
    <View className={classes} testID={testId} accessibilityRole="alert">
      {!!icon && <View className={cm.alertIconWrapper}>{icon as React.ReactNode}</View>}
      <View className={cm.alertContent}>
        {!!title && <Text className={cm.alertTitle}>{title as React.ReactNode}</Text>}
        {!!children && <Text className={cm.alertDescription}>{children as React.ReactNode}</Text>}
      </View>
      {dismissible && (
        <Pressable
          className={cm.alertDismiss}
          onPress={onDismiss}
          accessibilityLabel={t('ui.alert.dismiss', undefined, { defaultValue: 'Dismiss' })}
          accessibilityRole="button"
        >
          <Text>{t('ui.icon.close', undefined, { defaultValue: '✕' })}</Text>
        </Pressable>
      )}
    </View>
  )
}

// packages/app/frameworks/solid-ui/src/components/Alert.tsx
/**
 * Alert component.
 *
 * @module
 */

import { type Component, type JSX, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { AlertProps, ColorVariant } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.jsx'

const statusVariantMap: Record<ColorVariant, 'default' | 'info' | 'success' | 'warning' | 'error'> =
  {
    primary: 'default',
    secondary: 'default',
    success: 'success',
    warning: 'warning',
    error: 'error',
    info: 'info',
  }

const statusIconMap: Record<string, string> = {
  info: 'info-circle',
  success: 'check-circle',
  warning: 'exclamation-triangle',
  error: 'x-circle',
}

/**
 * Renders the Alert component.
 * @param props - The component props.
 * @returns The rendered alert JSX.
 */
export const Alert: Component<AlertProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'title',
    'status',
    'variant',
    'dismissible',
    'dismissLabel',
    'onDismiss',
    'icon',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const cmVariant = (): 'default' | 'info' | 'success' | 'warning' | 'error' => statusVariantMap[local.status || 'info'] || 'default'
  const iconName = (): string | undefined => statusIconMap[cmVariant()]

  const alertClasses = (): string => cm.cn(cm.alert({ variant: cmVariant() }), local.className)

  return (
    <div role="alert" class={alertClasses()} style={local.style} data-testid={local.testId}>
      <Show when={local.icon || iconName()}>
        <span class={cm.alertIconWrapper}>
          <Show when={local.icon} fallback={renderIcon(iconName()!, cm.iconMd)}>
            {local.icon as JSX.Element}
          </Show>
        </span>
      </Show>
      <div class={cm.alertContent}>
        <Show when={local.title}>
          <h5 class={cm.alertTitle}>{local.title}</h5>
        </Show>
        <div class={cm.alertDescription}>{local.children as JSX.Element}</div>
      </div>
      <Show when={local.dismissible}>
        <button
          type="button"
          onClick={local.onDismiss}
          class={cm.alertDismiss}
          aria-label={local.dismissLabel ?? t('ui.alert.dismiss', undefined, { defaultValue: 'Dismiss' })}
        >
          {renderIcon('x-mark', cm.iconSm)}
        </button>
      </Show>
    </div>
  )
}
