// packages/app/frameworks/react-ui/src/components/Avatar.tsx
/**
 * Avatar component.
 *
 * @module
 */

import React, { forwardRef, useState } from 'react'

import { t } from '@molecule/app-i18n'
import type { AvatarProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.js'

/**
 * Get initials from a name.
 * @param name - The full name to extract initials from.
 * @returns The uppercase initials string.
 */
function getInitials(name: string): string {
  return name
    .split(' ')
    .map((part) => part[0])
    .filter(Boolean)
    .slice(0, 2)
    .join('')
    .toUpperCase()
}

/**
 * Avatar component.
 */
export const Avatar = forwardRef<HTMLDivElement, AvatarProps>(
  ({ src, alt, name, size = 'md', rounded = true, fallback, className, style, testId }, ref) => {
    const [imageError, setImageError] = useState(false)

    const cm = getClassMap()
    const showFallback = !src || imageError

    const avatarSize = typeof size === 'number' ? undefined : size
    const containerClasses = cm.cn(cm.avatar({ size: avatarSize }), !rounded && cm.avatarSquare, className)

    const customSize = typeof size === 'number' ? { width: size, height: size } : undefined

    return (
      <div
        ref={ref}
        className={containerClasses}
        style={{ ...style, ...customSize }}
        data-testid={testId}
      >
        {!showFallback ? (
          <img
            src={src}
            alt={alt || name || t('ui.avatar.alt', undefined, { defaultValue: 'Avatar' })}
            className={cm.avatarImage}
            onError={() => setImageError(true)}
          />
        ) : (
          <div className={cm.avatarFallback}>
            {fallback ? (
              (fallback as React.ReactNode)
            ) : name ? (
              <span className={cm.avatarInitials}>{getInitials(name)}</span>
            ) : (
              renderIcon('user', cm.avatarFallbackIcon)
            )}
          </div>
        )}
      </div>
    )
  },
)

Avatar.displayName = 'Avatar'

// packages/app/frameworks/solid-ui/src/components/Avatar.tsx
/**
 * Avatar component.
 *
 * @module
 */

import { type Component, createSignal,type JSX, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { AvatarProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.jsx'

/**
 * Get initials from a name.
 * @param name - The full name to extract initials from.
 * @returns The uppercase initials string.
 */
function getInitials(name: string): string {
  return name
    .split(' ')
    .map((part) => part[0])
    .filter(Boolean)
    .slice(0, 2)
    .join('')
    .toUpperCase()
}

/**
 * Renders the Avatar component.
 * @param props - The component props.
 * @returns The rendered avatar JSX.
 */
export const Avatar: Component<AvatarProps> = (props) => {
  const [local] = splitProps(props, [
    'src',
    'alt',
    'name',
    'size',
    'rounded',
    'fallback',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const [imageError, setImageError] = createSignal(false)

  const showFallback = (): boolean => !local.src || imageError()
  const rounded = (): boolean => local.rounded ?? true

  const containerClasses = (): string =>
    cm.cn(
      cm.avatar({ size: typeof local.size === 'number' ? undefined : local.size }),
      !rounded() && cm.avatarSquare,
      local.className,
    )

  const customSize = (): { width: string; height: string } | undefined =>
    typeof local.size === 'number' ? { width: `${local.size}px`, height: `${local.size}px` } : undefined

  return (
    <div
      class={containerClasses()}
      style={{ ...local.style, ...customSize() }}
      data-testid={local.testId}
    >
      <Show
        when={!showFallback()}
        fallback={
          <div class={cm.avatarFallback}>
            <Show
              when={local.fallback}
              fallback={
                <Show
                  when={local.name}
                  fallback={renderIcon('user', cm.avatarFallbackIcon)}
                >
                  <span class={cm.avatarInitials}>{getInitials(local.name!)}</span>
                </Show>
              }
            >
              {local.fallback as JSX.Element}
            </Show>
          </div>
        }
      >
        <img
          src={local.src}
          alt={local.alt || local.name || t('ui.avatar.alt', undefined, { defaultValue: 'Avatar' })}
          class={cm.avatarImage}
          onError={() => setImageError(true)}
        />
      </Show>
    </div>
  )
}
