// packages/app/frameworks/react-ui/src/components/Card.tsx
/**
 * Card component.
 *
 * @module
 */

import React, { forwardRef } from 'react'

import type { CardProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

const variantMap: Record<string, 'default' | 'elevated' | 'outline' | 'ghost'> = {
  elevated: 'elevated',
  outlined: 'outline',
  filled: 'default',
}

// paddingMap removed — use cm.cardPadding(size) instead

/**
 * Card component.
 */
export const Card = forwardRef<HTMLDivElement, CardProps>(
  (
    {
      children,
      variant = 'elevated',
      interactive,
      padding = 'md',
      className,
      style,
      testId,
      onClick,
    },
    ref,
  ) => {
    const cm = getClassMap()
    const paddingClass = padding === 'none' ? '' : cm.cardPadding(padding)
    const cardVariant = variantMap[variant] || 'default'

    const cardClasses = cm.cn(
      cm.card({ variant: cardVariant }),
      paddingClass,
      interactive && cm.cardInteractive,
      className,
    )

    return (
      <div
        ref={ref}
        className={cardClasses}
        style={style}
        data-testid={testId}
        onClick={onClick as unknown as React.MouseEventHandler<HTMLDivElement>}
        role={interactive ? 'button' : undefined}
        tabIndex={interactive ? 0 : undefined}
      >
        {children as React.ReactNode}
      </div>
    )
  },
)

Card.displayName = 'Card'

/**
 * Card header component.
 */
export const CardHeader = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ children, className, ...props }, ref) => {
    const cm = getClassMap()

    return (
      <div ref={ref} className={cm.cn(cm.cardHeader, className)} {...props}>
        {children}
      </div>
    )
  },
)

CardHeader.displayName = 'CardHeader'

/**
 * Card title component.
 */
export const CardTitle = forwardRef<HTMLHeadingElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ children, className, ...props }, ref) => {
    const cm = getClassMap()

    return (
      <h3 ref={ref} className={cm.cn(cm.cardTitle, className)} {...props}>
        {children}
      </h3>
    )
  },
)

CardTitle.displayName = 'CardTitle'

/**
 * Card description component.
 */
export const CardDescription = forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ children, className, ...props }, ref) => {
  const cm = getClassMap()

  return (
    <p ref={ref} className={cm.cn(cm.cardDescription, className)} {...props}>
      {children}
    </p>
  )
})

CardDescription.displayName = 'CardDescription'

/**
 * Card content component.
 */
export const CardContent = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ children, className, ...props }, ref) => {
    const cm = getClassMap()

    return (
      <div ref={ref} className={cm.cn(cm.cardContent, className)} {...props}>
        {children}
      </div>
    )
  },
)

CardContent.displayName = 'CardContent'

/**
 * Card footer component.
 */
export const CardFooter = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ children, className, ...props }, ref) => {
    const cm = getClassMap()

    return (
      <div ref={ref} className={cm.cn(cm.cardFooter, className)} {...props}>
        {children}
      </div>
    )
  },
)

CardFooter.displayName = 'CardFooter'

// packages/app/frameworks/solid-ui/src/components/Card.tsx
/**
 * Card component.
 *
 * @module
 */

import { type Component, type JSX, splitProps } from 'solid-js'

import type { CardProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

const variantMap: Record<string, 'default' | 'elevated' | 'outline' | 'ghost'> = {
  elevated: 'elevated',
  outlined: 'outline',
  filled: 'default',
}

/**
 * Renders the Card component.
 * @param props - The component props.
 * @returns The rendered card JSX.
 */
export const Card: Component<CardProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'variant',
    'interactive',
    'padding',
    'className',
    'style',
    'testId',
    'onClick',
  ])

  const cm = getClassMap()
  const cmVariant = (): 'default' | 'elevated' | 'outline' | 'ghost' =>
    variantMap[local.variant || 'elevated'] || 'default'

  const cardClasses = (): string =>
    cm.cn(
      cm.card({ variant: cmVariant() }),
      cm.cardPadding(local.padding ?? 'md'),
      local.interactive && cm.cardInteractive,
      local.className,
    )

  return (
    <div
      class={cardClasses()}
      style={local.style}
      data-testid={local.testId}
      onClick={local.onClick as JSX.EventHandlerUnion<HTMLDivElement, MouseEvent>}
      role={local.interactive ? 'button' : undefined}
      tabIndex={local.interactive ? 0 : undefined}
    >
      {local.children as JSX.Element}
    </div>
  )
}

/**
 * Renders the CardHeader component.
 * @param props - The component props.
 * @returns The rendered card header JSX.
 */
export const CardHeader: Component<{ children?: JSX.Element; class?: string }> = (props) => {
  const cm = getClassMap()
  return <div class={cm.cn(cm.cardHeader, props.class)}>{props.children}</div>
}

/**
 * Renders the CardTitle component.
 * @param props - The component props.
 * @returns The rendered card title JSX.
 */
export const CardTitle: Component<{ children?: JSX.Element; class?: string }> = (props) => {
  const cm = getClassMap()
  return <h3 class={cm.cn(cm.cardTitle, props.class)}>{props.children}</h3>
}

/**
 * Card description component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const CardDescription: Component<{ children?: JSX.Element; class?: string }> = (props) => {
  const cm = getClassMap()
  return <p class={cm.cn(cm.cardDescription, props.class)}>{props.children}</p>
}

/**
 * Card content component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const CardContent: Component<{ children?: JSX.Element; class?: string }> = (props) => {
  const cm = getClassMap()
  return <div class={cm.cn(cm.cardContent, props.class)}>{props.children}</div>
}

/**
 * Card footer component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const CardFooter: Component<{ children?: JSX.Element; class?: string }> = (props) => {
  const cm = getClassMap()
  return <div class={cm.cn(cm.cardFooter, props.class)}>{props.children}</div>
}
