// packages/app/frameworks/react-native-ui/src/components/Checkbox.tsx
/**
 * Checkbox component for React Native.
 *
 * @module
 */

import React from 'react'
import { Pressable, Text, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { CheckboxProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders a Checkbox component.
 * @param root0 - Component props.
 * @param root0.label - Checkbox label text.
 * @param root0.checked - Whether checked.
 * @param root0.indeterminate - Whether indeterminate.
 * @param root0.onChange - Change handler.
 * @param root0.error - Error message.
 * @param root0.disabled - Whether disabled.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Checkbox element.
 */
export const Checkbox: React.FC<CheckboxProps> = ({
  label,
  checked,
  indeterminate,
  onChange,
  error,
  disabled,
  className,
  testId,
}) => {
  const cm = getClassMap()
  const boxClasses = cm.cn(cm.checkbox({ error: !!error }), className)

  return (
    <Pressable
      className={cm.controlLabel}
      onPress={() => {
        if (!disabled && onChange) {
          onChange({
            target: { checked: !checked },
          } as unknown as Event)
        }
      }}
      disabled={disabled}
      testID={testId}
      accessibilityRole="checkbox"
      accessibilityState={{
        checked: indeterminate ? 'mixed' : !!checked,
        disabled,
      }}
    >
      <View className={boxClasses}>
        {checked && !indeterminate && (
          <Text>{t('ui.icon.check', undefined, { defaultValue: '✓' })}</Text>
        )}
        {indeterminate && <Text>{t('ui.icon.minus', undefined, { defaultValue: '−' })}</Text>}
      </View>
      {!!label && (
        <Text className={cm.cn(cm.controlText, disabled && cm.controlDisabled)}>
          {label as React.ReactNode}
        </Text>
      )}
    </Pressable>
  )
}

// packages/app/frameworks/solid-ui/src/components/Checkbox.tsx
/**
 * Checkbox component.
 *
 * @module
 */

import { type Component, createEffect, type JSX, Show, splitProps } from 'solid-js'

import type { CheckboxProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the Checkbox component.
 * @param props - The component props.
 * @returns The rendered checkbox JSX.
 */
export const Checkbox: Component<CheckboxProps> = (props) => {
  const [local, rest] = splitProps(props, [
    'label',
    'checked',
    'indeterminate',
    'size',
    'error',
    'className',
    'style',
    'testId',
    'disabled',
    'name',
    'id',
    'onChange',
  ])

  const cm = getClassMap()
  // eslint-disable-next-line no-unassigned-vars -- assigned via SolidJS ref binding
  let checkboxRef: HTMLInputElement | undefined

  const checkboxId = (): string | undefined => local.id || local.name

  createEffect(() => {
    if (checkboxRef) {
      checkboxRef.indeterminate = !!local.indeterminate
    }
  })

  const checkboxClasses = (): string =>
    cm.cn(cm.checkbox({ error: !!local.error }), local.className)

  return (
    <div class={cm.formFieldWrapper}>
      <label class={cm.controlLabel}>
        <input
          ref={checkboxRef}
          type="checkbox"
          id={checkboxId()}
          name={local.name}
          checked={local.checked}
          disabled={local.disabled}
          data-state={local.checked ? 'checked' : 'unchecked'}
          aria-invalid={!!local.error}
          class={checkboxClasses()}
          style={local.style}
          data-testid={local.testId}
          onChange={local.onChange as JSX.EventHandlerUnion<HTMLInputElement, Event>}
          {...(rest as JSX.InputHTMLAttributes<HTMLInputElement>)}
        />
        <Show when={!!local.label}>
          <span class={cm.cn(cm.controlText, local.disabled && cm.controlDisabled)}>
            {local.label as JSX.Element}
          </span>
        </Show>
      </label>
      <Show when={local.error}>
        <p class={cm.cn(cm.formError, cm.sp('mt', 1))}>{local.error}</p>
      </Show>
    </div>
  )
}
