// packages/app/frameworks/react-native-ui/src/components/Form.tsx
/**
 * Form components for React Native.
 *
 * @module
 */

import React from 'react'
import { Text, View } from 'react-native'

import type { BaseProps, FormFieldProps, FormProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/** Local label props (not exported from `@molecule/app-ui`). */
interface LabelProps extends BaseProps {
  children?: unknown
  required?: boolean
}

/**
 * Renders a Form component.
 *
 * In React Native there is no `<form>` element. This is a View wrapper
 * that provides consistent spacing.
 * @param root0 - Component props.
 * @param root0.children - Form content.
 * @param root0.onSubmit - Submit handler (unused in RN).
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Form element.
 */
export const Form: React.FC<FormProps> = ({ children, onSubmit: _onSubmit, className, testId }) => {
  const cm = getClassMap()
  return (
    <View className={cm.cn(cm.formFieldset, className)} testID={testId}>
      {children as React.ReactNode}
    </View>
  )
}

/**
 * Renders a FormField component.
 * @param root0 - Component props.
 * @param root0.children - Field input content.
 * @param root0.label - Field label text.
 * @param root0.error - Error message.
 * @param root0.hint - Hint text.
 * @param root0.required - Whether required.
 * @param root0.className - CSS class name override.
 * @returns The rendered FormField element.
 */
export const FormField: React.FC<FormFieldProps> = ({
  children,
  label,
  error,
  hint,
  required,
  className,
}) => {
  const cm = getClassMap()
  return (
    <View className={cm.cn(cm.formField, className)}>
      {!!label && (
        <Text className={cm.cn(cm.labelBlock, cm.label({ required: !!required }))}>
          {label as React.ReactNode}
        </Text>
      )}
      <View className={cm.formFieldWrapper}>{children as React.ReactNode}</View>
      {!!error && typeof error === 'string' && <Text className={cm.formError}>{error}</Text>}
      {!!hint && !error && <Text className={cm.formHint}>{hint as React.ReactNode}</Text>}
    </View>
  )
}

/**
 * Renders a Label component.
 * @param root0 - Component props.
 * @param root0.children - Label content.
 * @param root0.required - Whether required.
 * @param root0.className - CSS class name override.
 * @returns The rendered Label element.
 */
export const Label: React.FC<LabelProps> = ({ children, required, className }) => {
  const cm = getClassMap()
  return (
    <Text className={cm.cn(cm.label({ required: !!required }), className)}>
      {children as React.ReactNode}
    </Text>
  )
}

// packages/app/frameworks/solid-ui/src/components/Form.tsx
/**
 * Form components.
 *
 * @module
 */

import { type Component, type JSX, Show, splitProps } from 'solid-js'

import type { FormFieldProps, FormProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Form component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Form: Component<FormProps> = (props) => {
  const [local, rest] = splitProps(props, [
    'children',
    'onFormSubmit',
    'submitting',
    'className',
    'style',
    'testId',
    'onSubmit',
    'action',
    'method',
    'noValidate',
  ])

  const cm = getClassMap()

  const handleSubmit: JSX.EventHandlerUnion<HTMLFormElement, Event> = (e) => {
    if (local.onFormSubmit) {
      e.preventDefault()
      const formData = new FormData(e.currentTarget)
      const data: Record<string, unknown> = {}
      formData.forEach((value, key) => {
        data[key] = value
      })
      local.onFormSubmit(data)
    }
    local.onSubmit?.(e as unknown as Event)
  }

  return (
    <form
      class={local.className}
      style={local.style}
      data-testid={local.testId}
      action={local.action}
      method={local.method}
      noValidate={local.noValidate}
      onSubmit={handleSubmit}
      {...(rest as JSX.FormHTMLAttributes<HTMLFormElement>)}
    >
      <fieldset disabled={local.submitting} class={cm.formFieldsetContents}>
        {local.children as JSX.Element}
      </fieldset>
    </form>
  )
}

/**
 * Form field wrapper component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const FormField: Component<FormFieldProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'label',
    'name',
    'error',
    'hint',
    'required',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()

  return (
    <div
      class={cm.cn(cm.formField, local.className)}
      style={local.style}
      data-testid={local.testId}
    >
      <Show when={local.label}>
        <label
          for={local.name}
          class={cm.cn(cm.label({ required: local.required }), cm.labelBlock)}
        >
          {local.label}
        </label>
      </Show>
      {local.children as JSX.Element}
      <Show when={local.error}>
        <p id={`${local.name}-error`} class={cm.formError}>
          {local.error}
        </p>
      </Show>
      <Show when={local.hint && !local.error}>
        <p id={`${local.name}-hint`} class={cm.formHint}>
          {local.hint}
        </p>
      </Show>
    </div>
  )
}

/**
 * Label component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Label: Component<{
  children?: JSX.Element
  required?: boolean
  class?: string
  for?: string
}> = (props) => {
  const cm = getClassMap()
  return (
    <label for={props.for} class={cm.cn(cm.label({ required: props.required }), props.class)}>
      {props.children}
    </label>
  )
}
