// packages/app/frameworks/react-native-ui/src/components/Input.tsx
/**
 * Input component for React Native.
 *
 * @module
 */

import React, { forwardRef, useCallback } from 'react'
import { Pressable, Text, TextInput, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { InputProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Text input component.
 */
export const Input = forwardRef<TextInput, InputProps>(
  (
    {
      label,
      error,
      hint,
      size = 'md',
      leftElement,
      rightElement,
      clearable,
      className,
      style,
      testId,
      disabled,
      type,
      placeholder,
      value,
      onChange,
      onFocus,
      onBlur,
      required,
      ..._rest
    },
    ref,
  ) => {
    const cm = getClassMap()
    const inputClasses = cm.cn(
      cm.input({ error: !!error, size }),
      !!leftElement && cm.inputPadLeft,
      !!(rightElement || clearable) && cm.inputPadRight,
      className,
    )

    const handleClear = useCallback(() => {
      if (onChange) {
        // Simulate a change event with empty value
        onChange({ target: { value: '' } } as unknown as Event)
      }
    }, [onChange])

    const secureTextEntry = type === 'password'
    const keyboardType =
      type === 'email'
        ? 'email-address'
        : type === 'number' || type === 'tel'
          ? 'numeric'
          : type === 'url'
            ? 'url'
            : 'default'

    return (
      <View className={cm.inputWrapper}>
        {!!label && (
          <Text className={cm.cn(cm.labelBlock, cm.label({ required: !!required }))}>
            {label as React.ReactNode}
          </Text>
        )}
        <View className={cm.inputInner}>
          {!!leftElement && (
            <View className={cm.inputLeftElement}>{leftElement as React.ReactNode}</View>
          )}
          <TextInput
            ref={ref}
            className={inputClasses}
            style={style as object}
            testID={testId}
            editable={!disabled}
            placeholder={placeholder}
            value={value as string | undefined}
            onChangeText={(text) => {
              if (onChange) {
                onChange({ target: { value: text } } as unknown as Event)
              }
            }}
            onFocus={onFocus as unknown as () => void}
            onBlur={onBlur as unknown as () => void}
            secureTextEntry={secureTextEntry}
            keyboardType={keyboardType}
            accessibilityLabel={typeof label === 'string' ? label : undefined}
          />
          {clearable && !!value && (
            <Pressable className={cm.inputClearButton} onPress={handleClear}>
              <Text>{t('ui.input.clear', undefined, { defaultValue: '×' })}</Text>
            </Pressable>
          )}
          {!!rightElement && !clearable && (
            <View className={cm.inputRightElement}>{rightElement as React.ReactNode}</View>
          )}
        </View>
        {!!error && typeof error === 'string' && <Text className={cm.formError}>{error}</Text>}
        {!!hint && !error && <Text className={cm.formHint}>{hint as React.ReactNode}</Text>}
      </View>
    )
  },
)

// packages/app/frameworks/solid-ui/src/components/Input.tsx
/**
 * Input component.
 *
 * @module
 */

import { type Component, type JSX, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { InputProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.jsx'

/**
 * Renders the Input component.
 * @param props - The component props.
 * @returns The rendered input JSX.
 */
export const Input: Component<InputProps> = (props) => {
  const [local, rest] = splitProps(props, [
    'type',
    'size',
    'label',
    'error',
    'hint',
    'leftElement',
    'rightElement',
    'clearable',
    'clearLabel',
    'onClear',
    'className',
    'style',
    'testId',
    'disabled',
    'required',
    'value',
    'defaultValue',
    'placeholder',
    'name',
    'id',
    'onChange',
    'onFocus',
    'onBlur',
  ])

  const cm = getClassMap()
  const inputId = (): string | undefined => local.id || local.name

  const inputClasses = (): string =>
    cm.cn(
      cm.input({ error: !!local.error, size: local.size }),
      !!local.leftElement && cm.inputPadLeft,
      !!(local.rightElement || local.clearable) && cm.inputPadRight,
      local.className,
    )

  return (
    <div class={cm.inputWrapper}>
      <Show when={local.label}>
        <label for={inputId()} class={cm.cn(cm.label({ required: local.required }), cm.labelBlock)}>
          {local.label}
        </label>
      </Show>
      <div class={cm.inputInner}>
        <Show when={!!local.leftElement}>
          <div class={cm.inputLeftElement}>{local.leftElement as JSX.Element}</div>
        </Show>
        <input
          type={local.type || 'text'}
          id={inputId()}
          name={local.name}
          value={(local.value as string) ?? ''}
          placeholder={local.placeholder}
          disabled={local.disabled}
          required={local.required}
          aria-invalid={!!local.error}
          aria-describedby={
            local.error ? `${inputId()}-error` : local.hint ? `${inputId()}-hint` : undefined
          }
          class={inputClasses()}
          style={local.style}
          data-testid={local.testId}
          onChange={local.onChange as JSX.EventHandlerUnion<HTMLInputElement, Event>}
          onFocus={local.onFocus as JSX.EventHandlerUnion<HTMLInputElement, FocusEvent>}
          onBlur={local.onBlur as JSX.EventHandlerUnion<HTMLInputElement, FocusEvent>}
          {...(rest as JSX.InputHTMLAttributes<HTMLInputElement>)}
        />
        <Show when={local.rightElement || (local.clearable && local.value)}>
          <div class={cm.inputRightElement}>
            <Show
              when={local.clearable && local.value}
              fallback={<span class={cm.textMuted}>{local.rightElement as JSX.Element}</span>}
            >
              <button
                type="button"
                onClick={local.onClear}
                class={cm.inputClearButton}
                aria-label={
                  local.clearLabel ?? t('ui.input.clear', undefined, { defaultValue: 'Clear' })
                }
              >
                {renderIcon('x-mark', cm.iconSm)}
              </button>
            </Show>
          </div>
        </Show>
      </div>
      <Show when={local.error}>
        <p id={`${inputId()}-error`} class={cm.formError}>
          {local.error}
        </p>
      </Show>
      <Show when={local.hint && !local.error}>
        <p id={`${inputId()}-hint`} class={cm.formHint}>
          {local.hint}
        </p>
      </Show>
    </div>
  )
}
