// packages/app/frameworks/react-ui/src/components/Layout.tsx
/**
 * Layout components.
 *
 * @module
 */

import React, { forwardRef } from 'react'

import type { ContainerProps, FlexProps, GridProps, Size, SpacerProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

// spacerSizeMap removed — use cm.spacer({ size, horizontal }) instead

/**
 * Container component.
 */
export const Container = forwardRef<HTMLDivElement, ContainerProps>(
  (
    { children, maxWidth = 'lg', centered = true, paddingX: _paddingX, className, style, testId },
    ref,
  ) => {
    const cm = getClassMap()
    const containerClasses = cm.cn(
      cm.container({ size: maxWidth as 'sm' | 'md' | 'lg' | 'xl' | '2xl' | 'full' }),
      centered && cm.mxAuto,
      className,
    )

    return (
      <div ref={ref} className={containerClasses} style={style} data-testid={testId}>
        {children as React.ReactNode}
      </div>
    )
  },
)

Container.displayName = 'Container'

/**
 * Flex container component.
 */
export const Flex = forwardRef<HTMLDivElement, FlexProps>(
  (
    { children, direction = 'row', justify, align, wrap, gap, className, style, testId, onClick },
    ref,
  ) => {
    const cm = getClassMap()

    // Map direction names to classMap API ('column' -> 'col', etc.)
    const dirMap: Record<string, 'row' | 'col' | 'row-reverse' | 'col-reverse'> = {
      row: 'row',
      column: 'col',
      'row-reverse': 'row-reverse',
      'column-reverse': 'col-reverse',
    }
    const cmDirection = dirMap[direction] || 'row'

    // Map gap to classMap accepted values
    const cmGap =
      typeof gap === 'string' && ['none', 'xs', 'sm', 'md', 'lg', 'xl'].includes(gap)
        ? (gap as 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl')
        : undefined

    const flexClasses = cm.cn(
      cm.flex({
        direction: cmDirection,
        align: align as FlexProps['align'],
        justify: justify as FlexProps['justify'],
        wrap: wrap as FlexProps['wrap'],
        gap: cmGap,
      }),
      className,
    )

    // If gap is a number or non-standard string, use inline style
    const gapStyle =
      typeof gap === 'number'
        ? { gap }
        : typeof gap === 'string' && !['none', 'xs', 'sm', 'md', 'lg', 'xl'].includes(gap)
          ? { gap }
          : undefined

    return (
      <div
        ref={ref}
        className={flexClasses}
        style={{ ...style, ...gapStyle }}
        data-testid={testId}
        onClick={onClick as unknown as React.MouseEventHandler<HTMLDivElement>}
      >
        {children as React.ReactNode}
      </div>
    )
  },
)

Flex.displayName = 'Flex'

/**
 * Grid container component.
 */
export const Grid = forwardRef<HTMLDivElement, GridProps>(
  ({ children, columns, rows, gap, columnGap, rowGap, className, style, testId }, ref) => {
    const cm = getClassMap()

    const cmCols = typeof columns === 'number' ? columns : undefined
    const cmGap =
      typeof gap === 'string' && ['none', 'xs', 'sm', 'md', 'lg', 'xl'].includes(gap)
        ? (gap as 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl')
        : undefined

    const gridClasses = cm.cn(cm.grid({ cols: cmCols, gap: cmGap }), className)

    const gridStyle: React.CSSProperties = {
      ...style,
      gridTemplateColumns: typeof columns === 'string' ? columns : undefined,
      gridTemplateRows: typeof rows === 'string' ? rows : undefined,
      gap:
        typeof gap === 'number'
          ? gap
          : typeof gap === 'string' && !['none', 'xs', 'sm', 'md', 'lg', 'xl'].includes(gap)
            ? gap
            : undefined,
      columnGap:
        typeof columnGap === 'number'
          ? columnGap
          : typeof columnGap === 'string'
            ? columnGap
            : undefined,
      rowGap: typeof rowGap === 'number' ? rowGap : typeof rowGap === 'string' ? rowGap : undefined,
    }

    return (
      <div ref={ref} className={gridClasses} style={gridStyle} data-testid={testId}>
        {children as React.ReactNode}
      </div>
    )
  },
)

Grid.displayName = 'Grid'

/**
 * Spacer component.
 */
export const Spacer = forwardRef<HTMLDivElement, SpacerProps>(
  ({ size = 'md', horizontal, className, style, testId }, ref) => {
    const cm = getClassMap()

    const isNamedSize = typeof size === 'string' && ['xs', 'sm', 'md', 'lg', 'xl'].includes(size)

    const spacerClasses = cm.cn(
      isNamedSize
        ? cm.spacer({ size: size as Size, horizontal: !!horizontal })
        : horizontal
          ? cm.displayInlineBlock
          : cm.displayBlock,
      className,
    )

    const sizeStyle: React.CSSProperties | undefined =
      typeof size === 'number'
        ? horizontal
          ? { width: size, height: '1px' }
          : { height: size, width: '1px' }
        : typeof size === 'string' && !isNamedSize
          ? horizontal
            ? { width: size }
            : { height: size }
          : undefined

    return (
      <div
        ref={ref}
        className={spacerClasses}
        style={{ ...style, ...sizeStyle }}
        data-testid={testId}
      />
    )
  },
)

Spacer.displayName = 'Spacer'

// packages/app/frameworks/solid-ui/src/components/Layout.tsx
/**
 * Layout components.
 *
 * @module
 */

import { type Component, type JSX, splitProps } from 'solid-js'

import type { ContainerProps, FlexProps, GridProps, Size, SpacerProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Container component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Container: Component<ContainerProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'maxWidth',
    'centered',
    'paddingX',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const centered = (): boolean => local.centered ?? true

  const containerClasses = (): string =>
    cm.cn(
      cm.container({ size: (local.maxWidth ?? 'lg') as Size | '2xl' | 'full' }),
      centered() && cm.mxAuto,
      local.className,
    )

  const containerStyle = (): JSX.CSSProperties | undefined => {
    const mw = local.maxWidth ?? 'lg'
    const standardSizes = ['sm', 'md', 'lg', 'xl', '2xl', 'full']
    const customMaxWidth = !standardSizes.includes(mw) ? mw : undefined
    return customMaxWidth ? { ...local.style, 'max-width': customMaxWidth } : local.style
  }

  return (
    <div class={containerClasses()} style={containerStyle()} data-testid={local.testId}>
      {local.children as JSX.Element}
    </div>
  )
}

/**
 * Flex container component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Flex: Component<FlexProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'direction',
    'justify',
    'align',
    'wrap',
    'gap',
    'className',
    'style',
    'testId',
    'onClick',
  ])

  const cm = getClassMap()

  const flexClasses = (): string =>
    cm.cn(
      cm.flex({
        direction:
          local.direction === 'column'
            ? 'col'
            : local.direction === 'column-reverse'
              ? 'col-reverse'
              : (local.direction as 'row' | 'row-reverse' | undefined),
        align: local.align,
        justify: local.justify,
        wrap: local.wrap,
        gap:
          typeof local.gap === 'string'
            ? (local.gap as 'xs' | 'sm' | 'md' | 'lg' | 'xl')
            : undefined,
      }),
      local.className,
    )

  const gapStyle = (): { gap: string } | undefined => {
    const gap = local.gap
    if (typeof gap === 'number') return { gap: `${gap}px` }
    if (typeof gap === 'string' && !['xs', 'sm', 'md', 'lg', 'xl', 'none'].includes(gap)) {
      return { gap }
    }
    return undefined
  }

  return (
    <div
      class={flexClasses()}
      style={{ ...local.style, ...gapStyle() }}
      data-testid={local.testId}
      onClick={local.onClick as JSX.EventHandlerUnion<HTMLDivElement, MouseEvent>}
    >
      {local.children as JSX.Element}
    </div>
  )
}

/**
 * Grid container component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Grid: Component<GridProps> = (props) => {
  const [local] = splitProps(props, [
    'children',
    'columns',
    'rows',
    'gap',
    'columnGap',
    'rowGap',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()

  const gridClasses = (): string =>
    cm.cn(
      cm.grid({
        cols: typeof local.columns === 'number' ? local.columns : undefined,
        gap:
          typeof local.gap === 'string'
            ? (local.gap as 'xs' | 'sm' | 'md' | 'lg' | 'xl')
            : undefined,
      }),
      typeof local.rows === 'number' && cm.gridRows(local.rows as number),
      local.className,
    )

  const gridStyle = (): JSX.CSSProperties => ({
    ...local.style,
    'grid-template-columns': typeof local.columns === 'string' ? local.columns : undefined,
    'grid-template-rows': typeof local.rows === 'string' ? local.rows : undefined,
    gap:
      typeof local.gap === 'number'
        ? `${local.gap}px`
        : typeof local.gap === 'string' &&
            !['xs', 'sm', 'md', 'lg', 'xl', 'none'].includes(local.gap)
          ? local.gap
          : undefined,
    'column-gap':
      typeof local.columnGap === 'number'
        ? `${local.columnGap}px`
        : typeof local.columnGap === 'string'
          ? local.columnGap
          : undefined,
    'row-gap':
      typeof local.rowGap === 'number'
        ? `${local.rowGap}px`
        : typeof local.rowGap === 'string'
          ? local.rowGap
          : undefined,
  })

  return (
    <div class={gridClasses()} style={gridStyle()} data-testid={local.testId}>
      {local.children as JSX.Element}
    </div>
  )
}

/**
 * Spacer component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Spacer: Component<SpacerProps> = (props) => {
  const [local] = splitProps(props, ['size', 'horizontal', 'className', 'style', 'testId'])

  const cm = getClassMap()
  const size = (): string | number => local.size ?? 'md'

  const spacerClasses = (): string => {
    const s = size()
    const isNamedSize = typeof s === 'string' && ['xs', 'sm', 'md', 'lg', 'xl'].includes(s)
    return cm.cn(
      isNamedSize
        ? cm.spacer({ size: s as Size, horizontal: local.horizontal })
        : local.horizontal
          ? cm.displayInlineBlock
          : cm.displayBlock,
      local.className,
    )
  }

  const sizeStyle = (): Record<string, string> | undefined => {
    const s = size()
    if (typeof s === 'number') {
      return local.horizontal
        ? { width: `${s}px`, height: '1px' }
        : { height: `${s}px`, width: '1px' }
    }
    if (typeof s === 'string' && !['xs', 'sm', 'md', 'lg', 'xl'].includes(s)) {
      return local.horizontal ? { width: s } : { height: s }
    }
    return undefined
  }

  return (
    <div
      class={spacerClasses()}
      style={{ ...local.style, ...sizeStyle() }}
      data-testid={local.testId}
    />
  )
}
