// packages/app/frameworks/angular-ui/src/components/radio-group.component.ts
/**
 * Angular RadioGroup UI component with UIClassMap-driven styling.
 *
 * @module
 */

import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core'

import type { RadioOption, Size, UIClassMap } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Angular RadioGroup UI component with UIClassMap-driven styling.
 */
@Component({
  selector: 'mol-radio-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      [class]="className"
      [style]="style"
      [attr.data-testid]="testId"
      role="radiogroup"
      [attr.aria-label]="label"
    >
      @if (label) {
        <div [class]="groupLabelClasses">{{ label }}</div>
      }
      <div [class]="directionClasses">
        @for (option of options; track option.value) {
          <label [class]="getOptionLabelClasses(option)">
            <input
              type="radio"
              [name]="label"
              [value]="option.value"
              [checked]="value === option.value"
              [disabled]="disabled || option.disabled"
              [attr.data-state]="value === option.value ? 'checked' : 'unchecked'"
              [class]="radioClasses"
              (change)="onRadioChange(option.value)"
            />
            <span [class]="cm.controlText">{{ option.label }}</span>
          </label>
        }
      </div>
      @if (error) {
        <p [class]="errorClasses">{{ error }}</p>
      }
    </div>
  `,
})
/**
 * Molecule Radio Group class.
 */
export class MoleculeRadioGroup {
  @Input() options: RadioOption<string>[] = []
  @Input() value?: string
  @Input() size?: Size
  @Input() label?: string
  @Input() direction: 'horizontal' | 'vertical' = 'vertical'
  @Input() error?: string
  @Input() className?: string
  @Input() style?: Record<string, string>
  @Input() testId?: string
  @Input() disabled = false

  @Output() valueChange = new EventEmitter<string>()

  /**
   * Retrieves the current UI class map.
   * @returns The UIClassMap instance for styling.
   */
  get cm(): UIClassMap {
    return getClassMap()
  }

  /**
   * Computes the CSS classes for the radio group label.
   * @returns The group label class name string.
   */
  get groupLabelClasses(): string {
    return this.cm.cn(this.cm.label({}), this.cm.radioGroupLabel)
  }

  /**
   * Computes the CSS classes for the layout direction.
   * @returns The direction layout class name string.
   */
  get directionClasses(): string {
    return this.cm.radioGroupLayout(this.direction)
  }

  /**
   * Computes the CSS classes for radio input elements.
   * @returns The radio input class name string.
   */
  get radioClasses(): string {
    return this.cm.cn(this.cm.radio({ error: !!this.error }), this.cm.cursorPointer)
  }

  /**
   * Computes the CSS classes for the error message.
   * @returns The error class name string.
   */
  get errorClasses(): string {
    return this.cm.cn(this.cm.formError, this.cm.sp('mt', 1))
  }

  /**
   * Computes the CSS classes for an individual radio option label.
   * @param option - The radio option to compute classes for.
   * @returns The option label class name string.
   */
  getOptionLabelClasses(option: RadioOption<string>): string {
    const isDisabled = this.disabled || option.disabled
    return this.cm.cn(this.cm.controlLabel, isDisabled && this.cm.controlDisabled)
  }

  /**
   * Handles radio option selection change.
   * @param optionValue - The value of the selected radio option.
   */
  onRadioChange(optionValue: string): void {
    this.valueChange.emit(optionValue)
  }
}

// packages/app/frameworks/solid-ui/src/components/RadioGroup.tsx
/**
 * RadioGroup component.
 *
 * @module
 */

import { type Component, For, type JSX, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { RadioGroupProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the RadioGroup component.
 * @param props - The component props.
 * @returns The rendered radio group JSX.
 */
export const RadioGroup: Component<RadioGroupProps<string>> = (props) => {
  const [local] = splitProps(props, [
    'options',
    'value',
    'onChange',
    'size',
    'label',
    'direction',
    'error',
    'className',
    'style',
    'testId',
    'disabled',
  ])

  const cm = getClassMap()
  const direction = (): 'horizontal' | 'vertical' => local.direction || 'vertical'

  const handleChange = (optionValue: string): void => {
    local.onChange?.(optionValue)
  }

  return (
    <div
      class={local.className}
      style={local.style}
      data-testid={local.testId}
      role="radiogroup"
      aria-label={
        local.label ?? t('ui.radioGroup.label', undefined, { defaultValue: 'Radio group' })
      }
    >
      <Show when={local.label}>
        <div class={cm.cn(cm.label({}), cm.radioGroupLabel)}>{local.label}</div>
      </Show>
      <div class={cm.radioGroupLayout(direction())}>
        <For each={local.options}>
          {(option) => {
            const isChecked = (): boolean => local.value === option.value
            const isDisabled = (): boolean | undefined => local.disabled || option.disabled

            return (
              <label class={cm.cn(cm.controlLabel, isDisabled() && cm.controlDisabled)}>
                <input
                  type="radio"
                  name={local.label}
                  value={option.value}
                  checked={isChecked()}
                  disabled={isDisabled()}
                  onChange={() => handleChange(option.value)}
                  data-state={isChecked() ? 'checked' : 'unchecked'}
                  class={cm.cn(cm.radio({ error: !!local.error }), cm.cursorPointer)}
                />
                <span class={cm.controlText}>{option.label as JSX.Element}</span>
              </label>
            )
          }}
        </For>
      </div>
      <Show when={local.error}>
        <p class={cm.cn(cm.formError, cm.sp('mt', 1))}>{local.error}</p>
      </Show>
    </div>
  )
}
