// packages/app/frameworks/react-ui/src/components/Separator.tsx
/**
 * Separator component.
 *
 * @module
 */

import React, { forwardRef } from 'react'

import type { BaseProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Props for the Separator component.
 */
export interface SeparatorProps extends BaseProps {
  /**
   * Orientation of the separator.
   */
  orientation?: 'horizontal' | 'vertical'

  /**
   * Decorative separators are purely visual.
   */
  decorative?: boolean
}

/**
 * Separator component.
 */
export const Separator = forwardRef<HTMLDivElement, SeparatorProps>(
  ({ orientation = 'horizontal', decorative = true, className, style, testId }, ref) => {
    const cm = getClassMap()
    const separatorClasses = cm.cn(cm.separator({ orientation }), className)

    return (
      <div
        ref={ref}
        role={decorative ? 'none' : 'separator'}
        aria-orientation={decorative ? undefined : orientation}
        className={separatorClasses}
        style={style}
        data-testid={testId}
      />
    )
  },
)

Separator.displayName = 'Separator'

// packages/app/frameworks/solid-ui/src/components/Separator.tsx
/**
 * Separator component.
 *
 * @module
 */

import { type Component, splitProps } from 'solid-js'

import type { SeparatorProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the Separator component.
 * @param props - The component props.
 * @returns The rendered separator JSX.
 */
export const Separator: Component<SeparatorProps> = (props) => {
  const [local] = splitProps(props, [
    'orientation',
    'decorative',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const orientation = (): 'horizontal' | 'vertical' => local.orientation || 'horizontal'
  const decorative = (): boolean => local.decorative ?? true

  const separatorClasses = (): string => cm.cn(cm.separator({ orientation: orientation() }), local.className)

  return (
    <div
      role={decorative() ? 'none' : 'separator'}
      aria-orientation={decorative() ? undefined : orientation()}
      class={separatorClasses()}
      style={local.style}
      data-testid={local.testId}
    />
  )
}
