// packages/app/frameworks/react-native-ui/src/components/Skeleton.tsx
/**
 * Skeleton components for React Native.
 *
 * @module
 */

import React, { useEffect, useRef } from 'react'
import { Animated, View,type ViewStyle } from 'react-native'

import type { SkeletonProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders a Skeleton component.
 * @param root0 - Component props.
 * @param root0.width - Skeleton width.
 * @param root0.height - Skeleton height.
 * @param root0.circle - Whether circular.
 * @param root0.animation - Animation type.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Skeleton element.
 */
export const Skeleton: React.FC<SkeletonProps> = ({
  width,
  height,
  circle,
  animation = 'pulse',
  className,
  testId,
}) => {
  const cm = getClassMap()
  const opacity = useRef(new Animated.Value(1)).current

  useEffect(() => {
    if (animation === 'pulse') {
      const pulse = Animated.loop(
        Animated.sequence([
          Animated.timing(opacity, { toValue: 0.5, duration: 1000, useNativeDriver: true }),
          Animated.timing(opacity, { toValue: 1, duration: 1000, useNativeDriver: true }),
        ]),
      )
      pulse.start()
      return () => pulse.stop()
    }
    return undefined
  }, [animation, opacity])

  const classes = cm.cn(
    cm.skeleton(),
    animation === 'wave' && cm.skeletonWave,
    animation === 'none' && cm.skeletonNone,
    circle && cm.skeletonCircle,
    className,
  )

  const sizeStyle: ViewStyle = {
    ...(width !== undefined ? { width: width as ViewStyle['width'] } : {}),
    ...(height !== undefined ? { height: height as ViewStyle['height'] } : {}),
    ...(circle && width ? { borderRadius: typeof width === 'number' ? width / 2 : undefined } : {}),
  }

  return (
    <Animated.View
      className={classes}
      style={[sizeStyle, { opacity: animation === 'pulse' ? opacity : 1 }]}
      testID={testId}
    />
  )
}

/**
 * Renders a SkeletonText component.
 * @param root0 - Component props.
 * @param root0.lines - Number of text lines.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered SkeletonText element.
 */
export const SkeletonText: React.FC<{
  lines?: number
  className?: string
  testId?: string
}> = ({ lines = 3, className, testId }) => {
  const cm = getClassMap()
  return (
    <View className={cm.cn(cm.skeletonTextContainer, className)} testID={testId}>
      {Array.from({ length: lines }, (_, i) => (
        <Skeleton key={i} height={12} width={i === lines - 1 ? '75%' : '100%'} />
      ))}
    </View>
  )
}

/**
 * Renders a SkeletonCircle component.
 * @param root0 - Component props.
 * @param root0.size - Circle diameter.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered SkeletonCircle element.
 */
export const SkeletonCircle: React.FC<{
  size?: number
  className?: string
  testId?: string
}> = ({ size = 40, className, testId }) => {
  return <Skeleton width={size} height={size} circle className={className} testId={testId} />
}

// packages/app/frameworks/solid-ui/src/components/Skeleton.tsx
/**
 * Skeleton component.
 *
 * @module
 */

import { type Component, For, splitProps } from 'solid-js'

import type { SkeletonProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Skeleton component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Skeleton: Component<SkeletonProps> = (props) => {
  const [local] = splitProps(props, [
    'width',
    'height',
    'circle',
    'borderRadius',
    'animation',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const animation = (): string => local.animation ?? 'pulse'

  const skeletonClasses = (): string =>
    cm.cn(
      cm.skeleton(),
      local.circle && cm.skeletonCircle,
      animation() === 'none' && cm.skeletonNone,
      animation() === 'wave' && cm.skeletonWave,
      local.className,
    )

  const computedStyle = (): Record<string, string | undefined> => {
    const style: Record<string, string | undefined> = {
      ...local.style,
      width: typeof local.width === 'number' ? `${local.width}px` : local.width,
      height: typeof local.height === 'number' ? `${local.height}px` : local.height,
      'border-radius': local.circle
        ? '9999px'
        : typeof local.borderRadius === 'number'
          ? `${local.borderRadius}px`
          : local.borderRadius,
    }

    // If circle, make width and height equal
    if (local.circle && local.width && !local.height) {
      style.height = style.width
    }

    return style
  }

  return <div class={skeletonClasses()} style={computedStyle()} data-testid={local.testId} />
}

/**
 * Skeleton text line.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const SkeletonText: Component<{ lines?: number; class?: string }> = (props) => {
  const cm = getClassMap()
  const lines = (): number => props.lines ?? 3
  return (
    <div class={cm.cn(cm.skeletonTextContainer, props.class)}>
      <For each={Array.from({ length: lines() })}>
        {(_, i) => <Skeleton height={16} width={i() === lines() - 1 ? '60%' : '100%'} />}
      </For>
    </div>
  )
}

/**
 * Skeleton circle (avatar placeholder).
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const SkeletonCircle: Component<{ size?: number; class?: string }> = (props) => {
  const size = (): number => props.size ?? 40
  return <Skeleton circle width={size()} height={size()} className={props.class} />
}
