// packages/app/frameworks/react-native-ui/src/components/Spinner.tsx
/**
 * Spinner component for React Native.
 *
 * @module
 */

import React from 'react'
import { ActivityIndicator, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { SpinnerProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

const sizeMap: Record<string, 'small' | 'large'> = {
  xs: 'small',
  sm: 'small',
  md: 'small',
  lg: 'large',
  xl: 'large',
}

/**
 * Renders a Spinner component.
 * @param root0 - Component props.
 * @param root0.size - Spinner size.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Spinner element.
 */
export const Spinner: React.FC<SpinnerProps> = ({ size = 'md', className, testId }) => {
  const cm = getClassMap()
  const classes = cm.cn(cm.spinner({ size }), className)

  return (
    <View
      className={classes}
      testID={testId}
      accessibilityRole="progressbar"
      accessibilityLabel={t('ui.spinner.loading', undefined, { defaultValue: 'Loading' })}
    >
      <ActivityIndicator size={sizeMap[size] || 'small'} />
    </View>
  )
}

// packages/app/frameworks/solid-ui/src/components/Spinner.tsx
/**
 * Spinner component.
 *
 * @module
 */

import { type Component, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { SpinnerProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the Spinner component.
 * @param props - The component props.
 * @returns The rendered spinner JSX.
 */
export const Spinner: Component<SpinnerProps> = (props) => {
  const [local] = splitProps(props, [
    'size',
    'color',
    'label',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const classes = (): string => cm.cn(cm.spinner({ size: local.size }), local.className)

  const colorStyle = (): Record<string, string> | undefined => {
    if (
      local.color &&
      typeof local.color === 'string' &&
      !['primary', 'secondary', 'success', 'warning', 'error', 'info'].includes(local.color)
    ) {
      return { 'border-color': local.color, 'border-top-color': 'transparent' }
    }
    return undefined
  }

  return (
    <div
      role="status"
      aria-label={local.label || t('ui.spinner.loading', undefined, { defaultValue: 'Loading' })}
      class={classes()}
      style={{ ...local.style, ...colorStyle() }}
      data-testid={local.testId}
    >
      <Show when={local.label}>
        <span class={cm.srOnly}>{local.label}</span>
      </Show>
    </div>
  )
}
