// packages/app/frameworks/react-native-ui/src/components/Switch.tsx
/**
 * Switch component for React Native.
 *
 * @module
 */

import React from 'react'
import { Switch as RNSwitch, Text, View } from 'react-native'

import type { SwitchProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders a Switch component.
 * @param root0 - Component props.
 * @param root0.label - Switch label text.
 * @param root0.checked - Whether checked.
 * @param root0.onChange - Change handler.
 * @param root0.size - Switch size (unused in RN).
 * @param root0.disabled - Whether disabled.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Switch element.
 */
export const Switch: React.FC<SwitchProps> = ({
  label,
  checked,
  onChange,
  size: _size = 'md',
  disabled,
  className,
  testId,
}) => {
  const cm = getClassMap()

  return (
    <View className={cm.cn(cm.controlLabel, className)} testID={testId}>
      <RNSwitch
        value={!!checked}
        onValueChange={(value) => {
          if (onChange) {
            onChange({ target: { checked: value } } as unknown as Event)
          }
        }}
        disabled={disabled}
        accessibilityRole="switch"
        accessibilityState={{ checked: !!checked, disabled }}
      />
      {!!label && (
        <Text className={cm.cn(cm.controlText, disabled && cm.controlDisabled)}>
          {label as React.ReactNode}
        </Text>
      )}
    </View>
  )
}

// packages/app/frameworks/solid-ui/src/components/Switch.tsx
/**
 * Switch component.
 *
 * @module
 */

import { type Component, type JSX, Show, splitProps } from 'solid-js'

import type { SwitchProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

/**
 * Renders the Switch component.
 * @param props - The component props.
 * @returns The rendered switch JSX.
 */
export const Switch: Component<SwitchProps> = (props) => {
  const [local, rest] = splitProps(props, [
    'label',
    'checked',
    'size',
    'color',
    'className',
    'style',
    'testId',
    'disabled',
    'onChange',
  ])

  const cm = getClassMap()
  const state = (): 'checked' | 'unchecked' => (local.checked ? 'checked' : 'unchecked')

  const handleClick = (): void => {
    if (!local.disabled) {
      // Simulate a change event
      const event = { target: { checked: !local.checked } } as unknown as Event
      local.onChange?.(event)
    }
  }

  return (
    <label class={cm.cn(cm.controlLabel, local.disabled && cm.controlDisabled)}>
      <button
        type="button"
        role="switch"
        aria-checked={local.checked}
        disabled={local.disabled}
        data-state={state()}
        onClick={handleClick}
        class={cm.cn(cm.switchBase({ size: local.size }), local.className)}
        style={local.style}
        data-testid={local.testId}
        {...(rest as JSX.ButtonHTMLAttributes<HTMLButtonElement>)}
      >
        <span data-state={state()} class={cm.switchThumb({ size: local.size })} />
      </button>
      <Show when={!!local.label}>
        <span class={cm.controlText}>{local.label as JSX.Element}</span>
      </Show>
    </label>
  )
}
