// packages/app/frameworks/react-native-ui/src/components/Table.tsx
/**
 * Table component for React Native.
 *
 * Uses FlatList for performant scrollable tables instead of HTML table elements.
 *
 * @module
 */

import React from 'react'
import { FlatList, Pressable, Text, View } from 'react-native'

import { t } from '@molecule/app-i18n'
import type { TableProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { Spinner } from './Spinner.js'

/**
 * Renders a Table component.
 * @param root0 - Component props.
 * @param root0.columns - Column definitions.
 * @param root0.data - Table row data.
 * @param root0.rowKey - Row key accessor.
 * @param root0.onRowClick - Row click handler.
 * @param root0.striped - Whether striped rows.
 * @param root0.bordered - Whether bordered.
 * @param root0.hoverable - Whether rows hoverable.
 * @param root0.loading - Whether loading.
 * @param root0.emptyContent - Empty state message.
 * @param root0.sort - Active sort state.
 * @param root0.onSort - Sort handler.
 * @param root0.className - CSS class name override.
 * @param root0.testId - Test identifier.
 * @returns The rendered Table element.
 */
export const Table: React.FC<TableProps<Record<string, unknown>>> = ({
  columns = [],
  data = [],
  rowKey,
  onRowClick,
  striped,
  bordered,
  hoverable,
  loading,
  emptyContent: emptyMessage,
  sort,
  onSort,
  className,
  testId,
}) => {
  const cm = getClassMap()

  const getRowKey = (row: Record<string, unknown>, index: number): string => {
    if (typeof rowKey === 'function') return String(rowKey(row))
    if (typeof rowKey === 'string' && row[rowKey] !== undefined) return String(row[rowKey])
    return String(index)
  }

  return (
    <View
      className={cm.cn(cm.tableWrapper, bordered && cm.tableBordered, className)}
      testID={testId}
    >
      {/* Header */}
      <View className={cm.cn(cm.tableHeader, cm.tableRow)}>
        {columns.map((col) => (
          <Pressable
            key={String(col.key)}
            className={cm.cn(cm.tableHead, col.sortable && cm.tableHeadSortable)}
            onPress={() =>
              col.sortable &&
              onSort &&
              onSort(
                String(col.key),
                sort?.key === String(col.key) && sort?.direction === 'asc' ? 'desc' : 'asc',
              )
            }
            disabled={!col.sortable}
          >
            <Text>{col.header as React.ReactNode}</Text>
            {col.sortable && sort?.key === String(col.key) && (
              <Text className={cm.tableSortIcon}>
                {sort.direction === 'asc'
                  ? t('ui.icon.sortAsc', undefined, { defaultValue: '↑' })
                  : t('ui.icon.sortDesc', undefined, { defaultValue: '↓' })}
              </Text>
            )}
          </Pressable>
        ))}
      </View>

      {/* Loading overlay */}
      {loading && (
        <View className={cm.tableLoadingOverlay}>
          <Spinner size="md" />
        </View>
      )}

      {/* Body */}
      {data.length === 0 && !loading ? (
        <View className={cm.tableEmptyCell}>
          <Text className={cm.textMuted}>
            {(emptyMessage as React.ReactNode) ||
              t('ui.table.empty', undefined, { defaultValue: 'No data' })}
          </Text>
        </View>
      ) : (
        <FlatList
          data={data}
          keyExtractor={(item, index) => getRowKey(item as Record<string, unknown>, index)}
          renderItem={({ item, index }) => {
            const row = item as Record<string, unknown>
            return (
              <Pressable
                className={cm.cn(
                  cm.tableRow,
                  striped && index % 2 === 1 && cm.tableRowStriped,
                  hoverable && cm.tableRowHoverable,
                  onRowClick && cm.tableRowClickable,
                )}
                onPress={() => onRowClick?.(row, index)}
                disabled={!onRowClick}
              >
                {columns.map((col) => {
                  const cellValue = row[col.key as string]
                  const rendered = col.render ? col.render(cellValue, row, index) : cellValue

                  return (
                    <View key={String(col.key)} className={cm.tableCell}>
                      <Text>{rendered as React.ReactNode}</Text>
                    </View>
                  )
                })}
              </Pressable>
            )
          }}
        />
      )}
    </View>
  )
}

// packages/app/frameworks/solid-ui/src/components/Table.tsx
/**
 * Table component.
 *
 * @module
 */

import { type Component, For, type JSX, Show, splitProps } from 'solid-js'

import { t } from '@molecule/app-i18n'
import type { TableColumn,TableProps } from '@molecule/app-ui'
import { getClassMap } from '@molecule/app-ui'

import { renderIcon } from '../utilities/renderIcon.js'
import { Spinner } from './Spinner.js'

/**
 * Table component.
 * @param props - The component props.
 * @returns The rendered component element.
 */
export const Table: Component<TableProps<Record<string, unknown>>> = (props) => {
  const [local] = splitProps(props, [
    'data',
    'columns',
    'rowKey',
    'bordered',
    'striped',
    'hoverable',
    'size',
    'emptyContent',
    'loading',
    'sort',
    'onSort',
    'onRowClick',
    'className',
    'style',
    'testId',
  ])

  const cm = getClassMap()
  const hoverable = (): boolean => local.hoverable ?? true

  const getCellValue = (
    row: Record<string, unknown>,
    column: TableColumn<Record<string, unknown>>,
    index: number,
  ): unknown => {
    if (column.render) {
      return column.render(row[column.key as string], row, index)
    }
    return row[column.key as string]
  }

  const handleSort = (column: TableColumn<Record<string, unknown>>): void => {
    if (!column.sortable || !local.onSort) return

    const key = column.key as string
    const currentDirection = local.sort?.key === key ? local.sort.direction : undefined
    const newDirection = currentDirection === 'asc' ? 'desc' : 'asc'
    local.onSort(key, newDirection)
  }

  const tableClasses = (): string => cm.cn(cm.table, local.bordered && cm.tableBordered, local.className)

  return (
    <div class={cm.tableWrapper}>
      <Show when={local.loading}>
        <div class={cm.tableLoadingOverlay}>
          <Spinner size="lg" />
        </div>
      </Show>
      <table class={tableClasses()} style={local.style} data-testid={local.testId}>
        <thead class={cm.tableHeader}>
          <tr class={cm.tableRow}>
            <For each={local.columns}>
              {(column) => (
                <th
                  class={cm.cn(
                    cm.tableHead,
                    column.align === 'center' && cm.textCenter,
                    column.align === 'right' && cm.textRight,
                    column.sortable && cm.tableHeadSortable,
                  )}
                  style={{ width: typeof column.width === 'number' ? `${column.width}px` : column.width }}
                  onClick={() => column.sortable && handleSort(column)}
                >
                  <div class={cm.tableSortWrapper}>
                    {column.header as JSX.Element}
                    <Show when={column.sortable && local.sort?.key === (column.key as string)}>
                      <span class={cm.tableSortIcon}>
                        <Show
                          when={local.sort!.direction === 'asc'}
                          fallback={renderIcon('chevron-down', cm.iconSm)}
                        >
                          {renderIcon('chevron-up', cm.iconSm)}
                        </Show>
                      </span>
                    </Show>
                  </div>
                </th>
              )}
            </For>
          </tr>
        </thead>
        <tbody class={cm.tableBody}>
          <Show
            when={local.data.length > 0}
            fallback={
              <tr>
                <td
                  colSpan={local.columns.length}
                  class={cm.tableEmptyCell}
                >
                  {(local.emptyContent as JSX.Element) || t('ui.table.empty', undefined, { defaultValue: 'No data available' })}
                </td>
              </tr>
            }
          >
            <For each={local.data}>
              {(row, rowIndex) => (
                <tr
                  class={cm.cn(
                    cm.tableRow,
                    local.striped && rowIndex() % 2 === 1 && cm.tableRowStriped,
                    hoverable() && cm.tableRowHoverable,
                    local.onRowClick && cm.tableRowClickable,
                  )}
                  onClick={() => local.onRowClick?.(row, rowIndex())}
                >
                  <For each={local.columns}>
                    {(column) => (
                      <td
                        class={cm.cn(
                          cm.tableCell,
                          column.align === 'center' && cm.textCenter,
                          column.align === 'right' && cm.textRight,
                        )}
                      >
                        {getCellValue(row, column, rowIndex()) as JSX.Element}
                      </td>
                    )}
                  </For>
                </tr>
              )}
            </For>
          </Show>
        </tbody>
      </table>
    </div>
  )
}
